// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: s_player.proto

package pbserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pbclient "roomcell/pkg/pb/pbclient"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色数据
type HallRoleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleTables []*DbTableData `protobuf:"bytes,1,rep,name=RoleTables,proto3" json:"RoleTables,omitempty"` // 角色相关的表
}

func (x *HallRoleData) Reset() {
	*x = HallRoleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HallRoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallRoleData) ProtoMessage() {}

func (x *HallRoleData) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallRoleData.ProtoReflect.Descriptor instead.
func (*HallRoleData) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{0}
}

func (x *HallRoleData) GetRoleTables() []*DbTableData {
	if x != nil {
		return x.RoleTables
	}
	return nil
}

// 创角数据
type CreateRoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	CchId   string `protobuf:"bytes,2,opt,name=CchId,proto3" json:"CchId,omitempty"`
	Level   int32  `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	UserID  int64  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *CreateRoleInfo) Reset() {
	*x = CreateRoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleInfo) ProtoMessage() {}

func (x *CreateRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleInfo.ProtoReflect.Descriptor instead.
func (*CreateRoleInfo) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateRoleInfo) GetCchId() string {
	if x != nil {
		return x.CchId
	}
	return ""
}

func (x *CreateRoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateRoleInfo) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

// ESMsgPlayerLoadRole = 1 // 加载角色数据
type ESMsgPlayerLoadRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID      int64           `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	WithCreate  bool            `protobuf:"varint,2,opt,name=WithCreate,proto3" json:"WithCreate,omitempty"`  // 如果不存在就创建
	CreateParam *CreateRoleInfo `protobuf:"bytes,3,opt,name=CreateParam,proto3" json:"CreateParam,omitempty"` // 创角参数
}

func (x *ESMsgPlayerLoadRoleReq) Reset() {
	*x = ESMsgPlayerLoadRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoadRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoadRoleReq) ProtoMessage() {}

func (x *ESMsgPlayerLoadRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoadRoleReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoadRoleReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{2}
}

func (x *ESMsgPlayerLoadRoleReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerLoadRoleReq) GetWithCreate() bool {
	if x != nil {
		return x.WithCreate
	}
	return false
}

func (x *ESMsgPlayerLoadRoleReq) GetCreateParam() *CreateRoleInfo {
	if x != nil {
		return x.CreateParam
	}
	return nil
}

type ESMsgPlayerLoadRoleRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleDetailData *HallRoleData `protobuf:"bytes,1,opt,name=RoleDetailData,proto3" json:"RoleDetailData,omitempty"` // 角色详细数据
}

func (x *ESMsgPlayerLoadRoleRep) Reset() {
	*x = ESMsgPlayerLoadRoleRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoadRoleRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoadRoleRep) ProtoMessage() {}

func (x *ESMsgPlayerLoadRoleRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoadRoleRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoadRoleRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{3}
}

func (x *ESMsgPlayerLoadRoleRep) GetRoleDetailData() *HallRoleData {
	if x != nil {
		return x.RoleDetailData
	}
	return nil
}

// ESMsgPlayerSaveRole = 2 // 保存角色数据
type ESMsgPlayerSaveRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID     int64          `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	RoleTables []*DbTableData `protobuf:"bytes,2,rep,name=RoleTables,proto3" json:"RoleTables,omitempty"` // 角色要保存的相关的表
}

func (x *ESMsgPlayerSaveRoleReq) Reset() {
	*x = ESMsgPlayerSaveRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerSaveRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerSaveRoleReq) ProtoMessage() {}

func (x *ESMsgPlayerSaveRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerSaveRoleReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerSaveRoleReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{4}
}

func (x *ESMsgPlayerSaveRoleReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerSaveRoleReq) GetRoleTables() []*DbTableData {
	if x != nil {
		return x.RoleTables
	}
	return nil
}

type ESMsgPlayerSaveRoleRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgPlayerSaveRoleRep) Reset() {
	*x = ESMsgPlayerSaveRoleRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerSaveRoleRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerSaveRoleRep) ProtoMessage() {}

func (x *ESMsgPlayerSaveRoleRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerSaveRoleRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerSaveRoleRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{5}
}

// ESMsgPlayerLoginHall = 3 // 登录大厅
type ESMsgPlayerLoginHallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64           `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`     // 账号id
	Account  string          `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`    // 账号
	CchId    string          `protobuf:"bytes,3,opt,name=CchId,proto3" json:"CchId,omitempty"`        // 渠道
	DataZone int32           `protobuf:"varint,4,opt,name=DataZone,proto3" json:"DataZone,omitempty"` // 数据节点区域
	GateInfo *ServerNodeInfo `protobuf:"bytes,5,opt,name=GateInfo,proto3" json:"GateInfo,omitempty"`  // 网关信息
}

func (x *ESMsgPlayerLoginHallReq) Reset() {
	*x = ESMsgPlayerLoginHallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoginHallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoginHallReq) ProtoMessage() {}

func (x *ESMsgPlayerLoginHallReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoginHallReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoginHallReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{6}
}

func (x *ESMsgPlayerLoginHallReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ESMsgPlayerLoginHallReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ESMsgPlayerLoginHallReq) GetCchId() string {
	if x != nil {
		return x.CchId
	}
	return ""
}

func (x *ESMsgPlayerLoginHallReq) GetDataZone() int32 {
	if x != nil {
		return x.DataZone
	}
	return 0
}

func (x *ESMsgPlayerLoginHallReq) GetGateInfo() *ServerNodeInfo {
	if x != nil {
		return x.GateInfo
	}
	return nil
}

type ESMsgPlayerLoginHallRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleData *pbclient.RoleInfo `protobuf:"bytes,1,opt,name=RoleData,proto3" json:"RoleData,omitempty"`
}

func (x *ESMsgPlayerLoginHallRep) Reset() {
	*x = ESMsgPlayerLoginHallRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoginHallRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoginHallRep) ProtoMessage() {}

func (x *ESMsgPlayerLoginHallRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoginHallRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoginHallRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{7}
}

func (x *ESMsgPlayerLoginHallRep) GetRoleData() *pbclient.RoleInfo {
	if x != nil {
		return x.RoleData
	}
	return nil
}

// ESMsgPlayerDisconnect = 4 // 玩家连接断开
type ESMsgPlayerDisconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Reason int32 `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"` // 断开原因
}

func (x *ESMsgPlayerDisconnectReq) Reset() {
	*x = ESMsgPlayerDisconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerDisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerDisconnectReq) ProtoMessage() {}

func (x *ESMsgPlayerDisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerDisconnectReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerDisconnectReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{8}
}

func (x *ESMsgPlayerDisconnectReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerDisconnectReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// ESMsgPlayerDisconnect = 4 // 玩家连接断开
type ESMsgPlayerDisconnectRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgPlayerDisconnectRep) Reset() {
	*x = ESMsgPlayerDisconnectRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerDisconnectRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerDisconnectRep) ProtoMessage() {}

func (x *ESMsgPlayerDisconnectRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerDisconnectRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerDisconnectRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{9}
}

// ESMsgPlayerKickOut    = 5 // 踢掉玩家
type ESMsgPlayerKickOutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Reason int32 `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *ESMsgPlayerKickOutReq) Reset() {
	*x = ESMsgPlayerKickOutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerKickOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerKickOutReq) ProtoMessage() {}

func (x *ESMsgPlayerKickOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerKickOutReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerKickOutReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{10}
}

func (x *ESMsgPlayerKickOutReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerKickOutReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type ESMsgPlayerKickOutRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgPlayerKickOutRep) Reset() {
	*x = ESMsgPlayerKickOutRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerKickOutRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerKickOutRep) ProtoMessage() {}

func (x *ESMsgPlayerKickOutRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerKickOutRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerKickOutRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{11}
}

var File_s_player_proto protoreflect.FileDescriptor

var file_s_player_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0c, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a,
	0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x45,
	0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x57, 0x69, 0x74, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x58, 0x0a, 0x16, 0x45, 0x53, 0x4d,
	0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x70, 0x12, 0x3e, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x16, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x16,
	0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x22, 0xb3, 0x01, 0x0a, 0x17, 0x45, 0x53, 0x4d, 0x73, 0x67,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x5a, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x49, 0x0a, 0x17,
	0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x52,
	0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x18, 0x45, 0x53, 0x4d, 0x73, 0x67,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x22,
	0x47, 0x0a, 0x15, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x69,
	0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x45, 0x53, 0x4d, 0x73,
	0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65,
	0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_player_proto_rawDescOnce sync.Once
	file_s_player_proto_rawDescData = file_s_player_proto_rawDesc
)

func file_s_player_proto_rawDescGZIP() []byte {
	file_s_player_proto_rawDescOnce.Do(func() {
		file_s_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_player_proto_rawDescData)
	})
	return file_s_player_proto_rawDescData
}

var file_s_player_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_s_player_proto_goTypes = []interface{}{
	(*HallRoleData)(nil),             // 0: pbserver.HallRoleData
	(*CreateRoleInfo)(nil),           // 1: pbserver.CreateRoleInfo
	(*ESMsgPlayerLoadRoleReq)(nil),   // 2: pbserver.ESMsgPlayerLoadRoleReq
	(*ESMsgPlayerLoadRoleRep)(nil),   // 3: pbserver.ESMsgPlayerLoadRoleRep
	(*ESMsgPlayerSaveRoleReq)(nil),   // 4: pbserver.ESMsgPlayerSaveRoleReq
	(*ESMsgPlayerSaveRoleRep)(nil),   // 5: pbserver.ESMsgPlayerSaveRoleRep
	(*ESMsgPlayerLoginHallReq)(nil),  // 6: pbserver.ESMsgPlayerLoginHallReq
	(*ESMsgPlayerLoginHallRep)(nil),  // 7: pbserver.ESMsgPlayerLoginHallRep
	(*ESMsgPlayerDisconnectReq)(nil), // 8: pbserver.ESMsgPlayerDisconnectReq
	(*ESMsgPlayerDisconnectRep)(nil), // 9: pbserver.ESMsgPlayerDisconnectRep
	(*ESMsgPlayerKickOutReq)(nil),    // 10: pbserver.ESMsgPlayerKickOutReq
	(*ESMsgPlayerKickOutRep)(nil),    // 11: pbserver.ESMsgPlayerKickOutRep
	(*DbTableData)(nil),              // 12: pbserver.DbTableData
	(*ServerNodeInfo)(nil),           // 13: pbserver.ServerNodeInfo
	(*pbclient.RoleInfo)(nil),        // 14: pbclient.RoleInfo
}
var file_s_player_proto_depIdxs = []int32{
	12, // 0: pbserver.HallRoleData.RoleTables:type_name -> pbserver.DbTableData
	1,  // 1: pbserver.ESMsgPlayerLoadRoleReq.CreateParam:type_name -> pbserver.CreateRoleInfo
	0,  // 2: pbserver.ESMsgPlayerLoadRoleRep.RoleDetailData:type_name -> pbserver.HallRoleData
	12, // 3: pbserver.ESMsgPlayerSaveRoleReq.RoleTables:type_name -> pbserver.DbTableData
	13, // 4: pbserver.ESMsgPlayerLoginHallReq.GateInfo:type_name -> pbserver.ServerNodeInfo
	14, // 5: pbserver.ESMsgPlayerLoginHallRep.RoleData:type_name -> pbclient.RoleInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_s_player_proto_init() }
func file_s_player_proto_init() {
	if File_s_player_proto != nil {
		return
	}
	file_s_db_proto_init()
	file_s_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_s_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HallRoleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoadRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoadRoleRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerSaveRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerSaveRoleRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoginHallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoginHallRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerDisconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerDisconnectRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerKickOutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerKickOutRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s_player_proto_goTypes,
		DependencyIndexes: file_s_player_proto_depIdxs,
		MessageInfos:      file_s_player_proto_msgTypes,
	}.Build()
	File_s_player_proto = out.File
	file_s_player_proto_rawDesc = nil
	file_s_player_proto_goTypes = nil
	file_s_player_proto_depIdxs = nil
}
