// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: s_room.proto

package pbserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pbclient "roomcell/pkg/pb/pbclient"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//ESMsgRoomCreate = 1 // 创建房间
type ESMsgRoomCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID     int64           `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	RoleID     int64           `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	RoleName   string          `protobuf:"bytes,3,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	GameName   string          `protobuf:"bytes,4,opt,name=GameName,proto3" json:"GameName,omitempty"`
	RoomType   int32           `protobuf:"varint,5,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	GateNode   *NetNode        `protobuf:"bytes,6,opt,name=GateNode,proto3" json:"GateNode,omitempty"`
	HallNode   *NetNode        `protobuf:"bytes,7,opt,name=HallNode,proto3" json:"HallNode,omitempty"`
	PlayerData *RoomPlayerData `protobuf:"bytes,8,opt,name=PlayerData,proto3" json:"PlayerData,omitempty"`
}

func (x *ESMsgRoomCreateReq) Reset() {
	*x = ESMsgRoomCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomCreateReq) ProtoMessage() {}

func (x *ESMsgRoomCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomCreateReq.ProtoReflect.Descriptor instead.
func (*ESMsgRoomCreateReq) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{0}
}

func (x *ESMsgRoomCreateReq) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *ESMsgRoomCreateReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgRoomCreateReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ESMsgRoomCreateReq) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *ESMsgRoomCreateReq) GetRoomType() int32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *ESMsgRoomCreateReq) GetGateNode() *NetNode {
	if x != nil {
		return x.GateNode
	}
	return nil
}

func (x *ESMsgRoomCreateReq) GetHallNode() *NetNode {
	if x != nil {
		return x.HallNode
	}
	return nil
}

func (x *ESMsgRoomCreateReq) GetPlayerData() *RoomPlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

type ESMsgRoomCreateRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZoneID     int32              `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	NodeType   int32              `protobuf:"varint,2,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeIndex  int32              `protobuf:"varint,3,opt,name=NodeIndex,proto3" json:"NodeIndex,omitempty"`
	RoomDetail *pbclient.RoomData `protobuf:"bytes,4,opt,name=RoomDetail,proto3" json:"RoomDetail,omitempty"`
}

func (x *ESMsgRoomCreateRep) Reset() {
	*x = ESMsgRoomCreateRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomCreateRep) ProtoMessage() {}

func (x *ESMsgRoomCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomCreateRep.ProtoReflect.Descriptor instead.
func (*ESMsgRoomCreateRep) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{1}
}

func (x *ESMsgRoomCreateRep) GetZoneID() int32 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *ESMsgRoomCreateRep) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *ESMsgRoomCreateRep) GetNodeIndex() int32 {
	if x != nil {
		return x.NodeIndex
	}
	return 0
}

func (x *ESMsgRoomCreateRep) GetRoomDetail() *pbclient.RoomData {
	if x != nil {
		return x.RoomDetail
	}
	return nil
}

// ESMsgRoomAutoDelete = 2 // 房间删除
type ESMsgRoomAutoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int64 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *ESMsgRoomAutoDeleteReq) Reset() {
	*x = ESMsgRoomAutoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomAutoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomAutoDeleteReq) ProtoMessage() {}

func (x *ESMsgRoomAutoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomAutoDeleteReq.ProtoReflect.Descriptor instead.
func (*ESMsgRoomAutoDeleteReq) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{2}
}

func (x *ESMsgRoomAutoDeleteReq) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ESMsgRoomAutoDeleteRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgRoomAutoDeleteRep) Reset() {
	*x = ESMsgRoomAutoDeleteRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomAutoDeleteRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomAutoDeleteRep) ProtoMessage() {}

func (x *ESMsgRoomAutoDeleteRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomAutoDeleteRep.ProtoReflect.Descriptor instead.
func (*ESMsgRoomAutoDeleteRep) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{3}
}

// ESMsgRoomEnter      = 3 // 进入房间
type ESMsgRoomEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID     int64           `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	RoleID     int64           `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	RoleName   string          `protobuf:"bytes,3,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	GameName   string          `protobuf:"bytes,4,opt,name=GameName,proto3" json:"GameName,omitempty"`
	GateNode   *NetNode        `protobuf:"bytes,5,opt,name=GateNode,proto3" json:"GateNode,omitempty"`
	HallNode   *NetNode        `protobuf:"bytes,6,opt,name=HallNode,proto3" json:"HallNode,omitempty"`
	PlayerData *RoomPlayerData `protobuf:"bytes,7,opt,name=PlayerData,proto3" json:"PlayerData,omitempty"`
}

func (x *ESMsgRoomEnterReq) Reset() {
	*x = ESMsgRoomEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomEnterReq) ProtoMessage() {}

func (x *ESMsgRoomEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomEnterReq.ProtoReflect.Descriptor instead.
func (*ESMsgRoomEnterReq) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{4}
}

func (x *ESMsgRoomEnterReq) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *ESMsgRoomEnterReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgRoomEnterReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ESMsgRoomEnterReq) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *ESMsgRoomEnterReq) GetGateNode() *NetNode {
	if x != nil {
		return x.GateNode
	}
	return nil
}

func (x *ESMsgRoomEnterReq) GetHallNode() *NetNode {
	if x != nil {
		return x.HallNode
	}
	return nil
}

func (x *ESMsgRoomEnterReq) GetPlayerData() *RoomPlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

type ESMsgRoomEnterRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZoneID     int32              `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	NodeType   int32              `protobuf:"varint,2,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeIndex  int32              `protobuf:"varint,3,opt,name=NodeIndex,proto3" json:"NodeIndex,omitempty"`
	RoomDetail *pbclient.RoomData `protobuf:"bytes,4,opt,name=RoomDetail,proto3" json:"RoomDetail,omitempty"`
}

func (x *ESMsgRoomEnterRep) Reset() {
	*x = ESMsgRoomEnterRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomEnterRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomEnterRep) ProtoMessage() {}

func (x *ESMsgRoomEnterRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomEnterRep.ProtoReflect.Descriptor instead.
func (*ESMsgRoomEnterRep) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{5}
}

func (x *ESMsgRoomEnterRep) GetZoneID() int32 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *ESMsgRoomEnterRep) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *ESMsgRoomEnterRep) GetNodeIndex() int32 {
	if x != nil {
		return x.NodeIndex
	}
	return 0
}

func (x *ESMsgRoomEnterRep) GetRoomDetail() *pbclient.RoomData {
	if x != nil {
		return x.RoomDetail
	}
	return nil
}

// ESMsgRoomLeave      = 4 // 离开房间
type ESMsgRoomLeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *ESMsgRoomLeaveReq) Reset() {
	*x = ESMsgRoomLeaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomLeaveReq) ProtoMessage() {}

func (x *ESMsgRoomLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomLeaveReq.ProtoReflect.Descriptor instead.
func (*ESMsgRoomLeaveReq) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{6}
}

func (x *ESMsgRoomLeaveReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type ESMsgRoomLeaveRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgRoomLeaveRep) Reset() {
	*x = ESMsgRoomLeaveRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomLeaveRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomLeaveRep) ProtoMessage() {}

func (x *ESMsgRoomLeaveRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomLeaveRep.ProtoReflect.Descriptor instead.
func (*ESMsgRoomLeaveRep) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{7}
}

// ESMsgRoomFind       = 5 // 获取房间信息
type ESMsgRoomFindReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int64 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *ESMsgRoomFindReq) Reset() {
	*x = ESMsgRoomFindReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomFindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomFindReq) ProtoMessage() {}

func (x *ESMsgRoomFindReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomFindReq.ProtoReflect.Descriptor instead.
func (*ESMsgRoomFindReq) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{8}
}

func (x *ESMsgRoomFindReq) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ESMsgRoomFindRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomBrief *pbclient.RoomSimple `protobuf:"bytes,1,opt,name=RoomBrief,proto3" json:"RoomBrief,omitempty"`
}

func (x *ESMsgRoomFindRep) Reset() {
	*x = ESMsgRoomFindRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgRoomFindRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgRoomFindRep) ProtoMessage() {}

func (x *ESMsgRoomFindRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgRoomFindRep.ProtoReflect.Descriptor instead.
func (*ESMsgRoomFindRep) Descriptor() ([]byte, []int) {
	return file_s_room_proto_rawDescGZIP(), []int{9}
}

func (x *ESMsgRoomFindRep) GetRoomBrief() *pbclient.RoomSimple {
	if x != nil {
		return x.RoomBrief
	}
	return nil
}

var File_s_room_proto protoreflect.FileDescriptor

var file_s_room_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x0e, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x02, 0x0a, 0x12, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f,
	0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d,
	0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x08, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a,
	0x08, 0x48, 0x61, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x08, 0x48, 0x61, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x0a,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x45, 0x53, 0x4d, 0x73, 0x67,
	0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x5a,
	0x6f, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x32, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0x30, 0x0a, 0x16, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d,
	0x41, 0x75, 0x74, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f,
	0x6f, 0x6d, 0x41, 0x75, 0x74, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x22,
	0x93, 0x02, 0x0a, 0x11, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a,
	0x08, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x08, 0x47, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x08,
	0x48, 0x61, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x74, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x08, 0x48, 0x61, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52,
	0x6f, 0x6f, 0x6d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x5a,
	0x6f, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x5a, 0x6f, 0x6e,
	0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x32, 0x0a,
	0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0x2b, 0x0a, 0x11, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x13,
	0x0a, 0x11, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x70, 0x22, 0x2a, 0x0a, 0x10, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22,
	0x46, 0x0a, 0x10, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x72, 0x69, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x09, 0x52, 0x6f,
	0x6f, 0x6d, 0x42, 0x72, 0x69, 0x65, 0x66, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x62, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_room_proto_rawDescOnce sync.Once
	file_s_room_proto_rawDescData = file_s_room_proto_rawDesc
)

func file_s_room_proto_rawDescGZIP() []byte {
	file_s_room_proto_rawDescOnce.Do(func() {
		file_s_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_room_proto_rawDescData)
	})
	return file_s_room_proto_rawDescData
}

var file_s_room_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_s_room_proto_goTypes = []interface{}{
	(*ESMsgRoomCreateReq)(nil),     // 0: pbserver.ESMsgRoomCreateReq
	(*ESMsgRoomCreateRep)(nil),     // 1: pbserver.ESMsgRoomCreateRep
	(*ESMsgRoomAutoDeleteReq)(nil), // 2: pbserver.ESMsgRoomAutoDeleteReq
	(*ESMsgRoomAutoDeleteRep)(nil), // 3: pbserver.ESMsgRoomAutoDeleteRep
	(*ESMsgRoomEnterReq)(nil),      // 4: pbserver.ESMsgRoomEnterReq
	(*ESMsgRoomEnterRep)(nil),      // 5: pbserver.ESMsgRoomEnterRep
	(*ESMsgRoomLeaveReq)(nil),      // 6: pbserver.ESMsgRoomLeaveReq
	(*ESMsgRoomLeaveRep)(nil),      // 7: pbserver.ESMsgRoomLeaveRep
	(*ESMsgRoomFindReq)(nil),       // 8: pbserver.ESMsgRoomFindReq
	(*ESMsgRoomFindRep)(nil),       // 9: pbserver.ESMsgRoomFindRep
	(*NetNode)(nil),                // 10: pbserver.NetNode
	(*RoomPlayerData)(nil),         // 11: pbserver.RoomPlayerData
	(*pbclient.RoomData)(nil),      // 12: pbclient.RoomData
	(*pbclient.RoomSimple)(nil),    // 13: pbclient.RoomSimple
}
var file_s_room_proto_depIdxs = []int32{
	10, // 0: pbserver.ESMsgRoomCreateReq.GateNode:type_name -> pbserver.NetNode
	10, // 1: pbserver.ESMsgRoomCreateReq.HallNode:type_name -> pbserver.NetNode
	11, // 2: pbserver.ESMsgRoomCreateReq.PlayerData:type_name -> pbserver.RoomPlayerData
	12, // 3: pbserver.ESMsgRoomCreateRep.RoomDetail:type_name -> pbclient.RoomData
	10, // 4: pbserver.ESMsgRoomEnterReq.GateNode:type_name -> pbserver.NetNode
	10, // 5: pbserver.ESMsgRoomEnterReq.HallNode:type_name -> pbserver.NetNode
	11, // 6: pbserver.ESMsgRoomEnterReq.PlayerData:type_name -> pbserver.RoomPlayerData
	12, // 7: pbserver.ESMsgRoomEnterRep.RoomDetail:type_name -> pbclient.RoomData
	13, // 8: pbserver.ESMsgRoomFindRep.RoomBrief:type_name -> pbclient.RoomSimple
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_s_room_proto_init() }
func file_s_room_proto_init() {
	if File_s_room_proto != nil {
		return
	}
	file_s_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_s_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomCreateRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomAutoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomAutoDeleteRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomEnterRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomLeaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomLeaveRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomFindReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgRoomFindRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s_room_proto_goTypes,
		DependencyIndexes: file_s_room_proto_depIdxs,
		MessageInfos:      file_s_room_proto_msgTypes,
	}.Build()
	File_s_room_proto = out.File
	file_s_room_proto_rawDesc = nil
	file_s_room_proto_goTypes = nil
	file_s_room_proto_depIdxs = nil
}
