// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_player.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Level  int32  `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Icon   int32  `protobuf:"varint,4,opt,name=Icon,proto3" json:"Icon,omitempty"`
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_c_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_c_player_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

// ECMsgPlayerLoginHall = 1 // 登录大厅
type ECMsgPlayerLoginHallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *ECMsgPlayerLoginHallReq) Reset() {
	*x = ECMsgPlayerLoginHallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgPlayerLoginHallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgPlayerLoginHallReq) ProtoMessage() {}

func (x *ECMsgPlayerLoginHallReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgPlayerLoginHallReq.ProtoReflect.Descriptor instead.
func (*ECMsgPlayerLoginHallReq) Descriptor() ([]byte, []int) {
	return file_c_player_proto_rawDescGZIP(), []int{1}
}

func (x *ECMsgPlayerLoginHallReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ECMsgPlayerLoginHallRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleData *RoleInfo `protobuf:"bytes,1,opt,name=RoleData,proto3" json:"RoleData,omitempty"`
}

func (x *ECMsgPlayerLoginHallRsp) Reset() {
	*x = ECMsgPlayerLoginHallRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgPlayerLoginHallRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgPlayerLoginHallRsp) ProtoMessage() {}

func (x *ECMsgPlayerLoginHallRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgPlayerLoginHallRsp.ProtoReflect.Descriptor instead.
func (*ECMsgPlayerLoginHallRsp) Descriptor() ([]byte, []int) {
	return file_c_player_proto_rawDescGZIP(), []int{2}
}

func (x *ECMsgPlayerLoginHallRsp) GetRoleData() *RoleInfo {
	if x != nil {
		return x.RoleData
	}
	return nil
}

// ECMsgPlayerKeepHeart = 2 // 心跳
type ECMsgPlayerKeepHeartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgPlayerKeepHeartReq) Reset() {
	*x = ECMsgPlayerKeepHeartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgPlayerKeepHeartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgPlayerKeepHeartReq) ProtoMessage() {}

func (x *ECMsgPlayerKeepHeartReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgPlayerKeepHeartReq.ProtoReflect.Descriptor instead.
func (*ECMsgPlayerKeepHeartReq) Descriptor() ([]byte, []int) {
	return file_c_player_proto_rawDescGZIP(), []int{3}
}

type ECMsgPlayerKeepHeartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgPlayerKeepHeartRsp) Reset() {
	*x = ECMsgPlayerKeepHeartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgPlayerKeepHeartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgPlayerKeepHeartRsp) ProtoMessage() {}

func (x *ECMsgPlayerKeepHeartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgPlayerKeepHeartRsp.ProtoReflect.Descriptor instead.
func (*ECMsgPlayerKeepHeartRsp) Descriptor() ([]byte, []int) {
	return file_c_player_proto_rawDescGZIP(), []int{4}
}

var File_c_player_proto protoreflect.FileDescriptor

var file_c_player_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x08, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x17,
	0x45, 0x43, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x49, 0x0a,
	0x17, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x43, 0x4d, 0x73,
	0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x65, 0x65, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4b, 0x65, 0x65, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x42, 0x1a,
	0x5a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_c_player_proto_rawDescOnce sync.Once
	file_c_player_proto_rawDescData = file_c_player_proto_rawDesc
)

func file_c_player_proto_rawDescGZIP() []byte {
	file_c_player_proto_rawDescOnce.Do(func() {
		file_c_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_player_proto_rawDescData)
	})
	return file_c_player_proto_rawDescData
}

var file_c_player_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_c_player_proto_goTypes = []interface{}{
	(*RoleInfo)(nil),                // 0: pbclient.RoleInfo
	(*ECMsgPlayerLoginHallReq)(nil), // 1: pbclient.ECMsgPlayerLoginHallReq
	(*ECMsgPlayerLoginHallRsp)(nil), // 2: pbclient.ECMsgPlayerLoginHallRsp
	(*ECMsgPlayerKeepHeartReq)(nil), // 3: pbclient.ECMsgPlayerKeepHeartReq
	(*ECMsgPlayerKeepHeartRsp)(nil), // 4: pbclient.ECMsgPlayerKeepHeartRsp
}
var file_c_player_proto_depIdxs = []int32{
	0, // 0: pbclient.ECMsgPlayerLoginHallRsp.RoleData:type_name -> pbclient.RoleInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_c_player_proto_init() }
func file_c_player_proto_init() {
	if File_c_player_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgPlayerLoginHallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgPlayerLoginHallRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgPlayerKeepHeartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgPlayerKeepHeartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_player_proto_goTypes,
		DependencyIndexes: file_c_player_proto_depIdxs,
		MessageInfos:      file_c_player_proto_msgTypes,
	}.Build()
	File_c_player_proto = out.File
	file_c_player_proto_rawDesc = nil
	file_c_player_proto_goTypes = nil
	file_c_player_proto_depIdxs = nil
}
