// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_room_number_bomb.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数字炸弹
type ENumberBombStep int32

const (
	ENumberBombStep_ENumberBombStepReady       ENumberBombStep = 0 // 准备阶段
	ENumberBombStep_ENumberBombStepGenNumber   ENumberBombStep = 1 // 生成系统数字
	ENumberBombStep_ENumberBombStepGuessNumber ENumberBombStep = 2 // 猜数字阶段
	ENumberBombStep_ENumberBombStepTurnEnd     ENumberBombStep = 3 // 本轮结束阶段
	ENumberBombStep_ENumberBombStepGameEnd     ENumberBombStep = 4 // 游戏结束
)

// Enum value maps for ENumberBombStep.
var (
	ENumberBombStep_name = map[int32]string{
		0: "ENumberBombStepReady",
		1: "ENumberBombStepGenNumber",
		2: "ENumberBombStepGuessNumber",
		3: "ENumberBombStepTurnEnd",
		4: "ENumberBombStepGameEnd",
	}
	ENumberBombStep_value = map[string]int32{
		"ENumberBombStepReady":       0,
		"ENumberBombStepGenNumber":   1,
		"ENumberBombStepGuessNumber": 2,
		"ENumberBombStepTurnEnd":     3,
		"ENumberBombStepGameEnd":     4,
	}
)

func (x ENumberBombStep) Enum() *ENumberBombStep {
	p := new(ENumberBombStep)
	*p = x
	return p
}

func (x ENumberBombStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENumberBombStep) Descriptor() protoreflect.EnumDescriptor {
	return file_c_room_number_bomb_proto_enumTypes[0].Descriptor()
}

func (ENumberBombStep) Type() protoreflect.EnumType {
	return &file_c_room_number_bomb_proto_enumTypes[0]
}

func (x ENumberBombStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENumberBombStep.Descriptor instead.
func (ENumberBombStep) EnumDescriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{0}
}

// 玩家游戏数据
type NumberBombPlayerGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID       int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`             // 角色id
	Nickname     string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`          // 昵称
	Icon         int32  `protobuf:"varint,3,opt,name=Icon,proto3" json:"Icon,omitempty"`                 // 图像
	IsOnline     bool   `protobuf:"varint,4,opt,name=IsOnline,proto3" json:"IsOnline,omitempty"`         // 是否在线
	PlayerNumber int32  `protobuf:"varint,5,opt,name=PlayerNumber,proto3" json:"PlayerNumber,omitempty"` // 玩家编号
	Ready        int32  `protobuf:"varint,6,opt,name=Ready,proto3" json:"Ready,omitempty"`               // 准备状态 0-未准备 1-准备了
	GuessNum     int32  `protobuf:"varint,7,opt,name=GuessNum,proto3" json:"GuessNum,omitempty"`         // 本次游戏猜的数字
}

func (x *NumberBombPlayerGameData) Reset() {
	*x = NumberBombPlayerGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberBombPlayerGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberBombPlayerGameData) ProtoMessage() {}

func (x *NumberBombPlayerGameData) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberBombPlayerGameData.ProtoReflect.Descriptor instead.
func (*NumberBombPlayerGameData) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{0}
}

func (x *NumberBombPlayerGameData) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *NumberBombPlayerGameData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *NumberBombPlayerGameData) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *NumberBombPlayerGameData) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *NumberBombPlayerGameData) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

func (x *NumberBombPlayerGameData) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *NumberBombPlayerGameData) GetGuessNum() int32 {
	if x != nil {
		return x.GuessNum
	}
	return 0
}

// 房间游戏数据
type RoomNumberBombDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomStep        int32                               `protobuf:"varint,1,opt,name=RoomStep,proto3" json:"RoomStep,omitempty"`                                                                                                       // 房间游戏阶段 对应 EUndercoverStep
	StepTime        int64                               `protobuf:"varint,2,opt,name=StepTime,proto3" json:"StepTime,omitempty"`                                                                                                       // 阶段对应的开始时间戳
	PlayersGameData map[int64]*NumberBombPlayerGameData `protobuf:"bytes,3,rep,name=PlayersGameData,proto3" json:"PlayersGameData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 玩家游戏数据
	TalkRoleID      int64                               `protobuf:"varint,4,opt,name=TalkRoleID,proto3" json:"TalkRoleID,omitempty"`                                                                                                   // 当前发言玩家
	TalkRoleNumber  int32                               `protobuf:"varint,5,opt,name=TalkRoleNumber,proto3" json:"TalkRoleNumber,omitempty"`                                                                                           // 当前发言玩家编号
	BombRoleID      int64                               `protobuf:"varint,6,opt,name=BombRoleID,proto3" json:"BombRoleID,omitempty"`                                                                                                   // 猜中炸弹的玩家id
	MinNumber       int32                               `protobuf:"varint,7,opt,name=MinNumber,proto3" json:"MinNumber,omitempty"`                                                                                                     // 数字范围-最小值
	MaxNumber       int32                               `protobuf:"varint,8,opt,name=MaxNumber,proto3" json:"MaxNumber,omitempty"`                                                                                                     // 数字范围-最大值
	Turn            int32                               `protobuf:"varint,9,opt,name=Turn,proto3" json:"Turn,omitempty"`                                                                                                               // 当前轮数,从1开始
	MaxTurn         int32                               `protobuf:"varint,10,opt,name=MaxTurn,proto3" json:"MaxTurn,omitempty"`                                                                                                        // 最大轮数
	SysNumber       int32                               `protobuf:"varint,11,opt,name=SysNumber,proto3" json:"SysNumber,omitempty"`                                                                                                    // 系统生成的数字
}

func (x *RoomNumberBombDetail) Reset() {
	*x = RoomNumberBombDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomNumberBombDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomNumberBombDetail) ProtoMessage() {}

func (x *RoomNumberBombDetail) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomNumberBombDetail.ProtoReflect.Descriptor instead.
func (*RoomNumberBombDetail) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{1}
}

func (x *RoomNumberBombDetail) GetRoomStep() int32 {
	if x != nil {
		return x.RoomStep
	}
	return 0
}

func (x *RoomNumberBombDetail) GetStepTime() int64 {
	if x != nil {
		return x.StepTime
	}
	return 0
}

func (x *RoomNumberBombDetail) GetPlayersGameData() map[int64]*NumberBombPlayerGameData {
	if x != nil {
		return x.PlayersGameData
	}
	return nil
}

func (x *RoomNumberBombDetail) GetTalkRoleID() int64 {
	if x != nil {
		return x.TalkRoleID
	}
	return 0
}

func (x *RoomNumberBombDetail) GetTalkRoleNumber() int32 {
	if x != nil {
		return x.TalkRoleNumber
	}
	return 0
}

func (x *RoomNumberBombDetail) GetBombRoleID() int64 {
	if x != nil {
		return x.BombRoleID
	}
	return 0
}

func (x *RoomNumberBombDetail) GetMinNumber() int32 {
	if x != nil {
		return x.MinNumber
	}
	return 0
}

func (x *RoomNumberBombDetail) GetMaxNumber() int32 {
	if x != nil {
		return x.MaxNumber
	}
	return 0
}

func (x *RoomNumberBombDetail) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *RoomNumberBombDetail) GetMaxTurn() int32 {
	if x != nil {
		return x.MaxTurn
	}
	return 0
}

func (x *RoomNumberBombDetail) GetSysNumber() int32 {
	if x != nil {
		return x.SysNumber
	}
	return 0
}

// ECMsgGamePushNumberBombRoomData     = 50 // 数字炸弹-推送房间游戏数据
type ECMsgGamePushNumberBombRoomDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomGameData *RoomNumberBombDetail `protobuf:"bytes,1,opt,name=RoomGameData,proto3" json:"RoomGameData,omitempty"`
}

func (x *ECMsgGamePushNumberBombRoomDataNotify) Reset() {
	*x = ECMsgGamePushNumberBombRoomDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushNumberBombRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushNumberBombRoomDataNotify) ProtoMessage() {}

func (x *ECMsgGamePushNumberBombRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushNumberBombRoomDataNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushNumberBombRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{2}
}

func (x *ECMsgGamePushNumberBombRoomDataNotify) GetRoomGameData() *RoomNumberBombDetail {
	if x != nil {
		return x.RoomGameData
	}
	return nil
}

// ECMsgGamePushNumberBombGuesserChange    = 51 // 数字炸弹-猜数字玩家变更
type ECMsgGamePushNumberBombGuesserChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkRoleID int64 `protobuf:"varint,1,opt,name=TalkRoleID,proto3" json:"TalkRoleID,omitempty"` // 当前发言玩家
}

func (x *ECMsgGamePushNumberBombGuesserChangeNotify) Reset() {
	*x = ECMsgGamePushNumberBombGuesserChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushNumberBombGuesserChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushNumberBombGuesserChangeNotify) ProtoMessage() {}

func (x *ECMsgGamePushNumberBombGuesserChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushNumberBombGuesserChangeNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushNumberBombGuesserChangeNotify) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{3}
}

func (x *ECMsgGamePushNumberBombGuesserChangeNotify) GetTalkRoleID() int64 {
	if x != nil {
		return x.TalkRoleID
	}
	return 0
}

// ECMsgGamePushNumberBombRangeChange      = 52 // 数字炸弹-数字范围变更
type ECMsgGamePushNumberBombRangeChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinNumber int32 `protobuf:"varint,1,opt,name=MinNumber,proto3" json:"MinNumber,omitempty"`
	MaxNumber int32 `protobuf:"varint,2,opt,name=MaxNumber,proto3" json:"MaxNumber,omitempty"`
}

func (x *ECMsgGamePushNumberBombRangeChangeNotify) Reset() {
	*x = ECMsgGamePushNumberBombRangeChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushNumberBombRangeChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushNumberBombRangeChangeNotify) ProtoMessage() {}

func (x *ECMsgGamePushNumberBombRangeChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushNumberBombRangeChangeNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushNumberBombRangeChangeNotify) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{4}
}

func (x *ECMsgGamePushNumberBombRangeChangeNotify) GetMinNumber() int32 {
	if x != nil {
		return x.MinNumber
	}
	return 0
}

func (x *ECMsgGamePushNumberBombRangeChangeNotify) GetMaxNumber() int32 {
	if x != nil {
		return x.MaxNumber
	}
	return 0
}

// ECMsgGameNumberBombGuess            = 53 // 数字炸弹-猜数字
type ECMsgGameNumberBombGuessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuessNumber int32 `protobuf:"varint,1,opt,name=GuessNumber,proto3" json:"GuessNumber,omitempty"` // 猜测的数字
}

func (x *ECMsgGameNumberBombGuessReq) Reset() {
	*x = ECMsgGameNumberBombGuessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameNumberBombGuessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameNumberBombGuessReq) ProtoMessage() {}

func (x *ECMsgGameNumberBombGuessReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameNumberBombGuessReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameNumberBombGuessReq) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{5}
}

func (x *ECMsgGameNumberBombGuessReq) GetGuessNumber() int32 {
	if x != nil {
		return x.GuessNumber
	}
	return 0
}

type ECMsgGameNumberBombGuessRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameNumberBombGuessRsp) Reset() {
	*x = ECMsgGameNumberBombGuessRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameNumberBombGuessRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameNumberBombGuessRsp) ProtoMessage() {}

func (x *ECMsgGameNumberBombGuessRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameNumberBombGuessRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameNumberBombGuessRsp) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{6}
}

// ECMsgGamePushNumberBombGuess        = 54 // 数字炸弹-猜数字推送
type ECMsgGamePushNumberBombGuessNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Talker      *RoomTalker `protobuf:"bytes,1,opt,name=Talker,proto3" json:"Talker,omitempty"`            // 说话的人
	GuessNumber int32       `protobuf:"varint,2,opt,name=GuessNumber,proto3" json:"GuessNumber,omitempty"` // 猜测的数字
}

func (x *ECMsgGamePushNumberBombGuessNotify) Reset() {
	*x = ECMsgGamePushNumberBombGuessNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushNumberBombGuessNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushNumberBombGuessNotify) ProtoMessage() {}

func (x *ECMsgGamePushNumberBombGuessNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushNumberBombGuessNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushNumberBombGuessNotify) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{7}
}

func (x *ECMsgGamePushNumberBombGuessNotify) GetTalker() *RoomTalker {
	if x != nil {
		return x.Talker
	}
	return nil
}

func (x *ECMsgGamePushNumberBombGuessNotify) GetGuessNumber() int32 {
	if x != nil {
		return x.GuessNumber
	}
	return 0
}

// ECMsgGameNumberBombChoosePunishment = 55 // 数字炸弹-选择惩罚
type ECMsgGameNumberBombChoosePunishmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PunishmentID int32 `protobuf:"varint,1,opt,name=PunishmentID,proto3" json:"PunishmentID,omitempty"` // 惩罚id
}

func (x *ECMsgGameNumberBombChoosePunishmentReq) Reset() {
	*x = ECMsgGameNumberBombChoosePunishmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameNumberBombChoosePunishmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameNumberBombChoosePunishmentReq) ProtoMessage() {}

func (x *ECMsgGameNumberBombChoosePunishmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameNumberBombChoosePunishmentReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameNumberBombChoosePunishmentReq) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{8}
}

func (x *ECMsgGameNumberBombChoosePunishmentReq) GetPunishmentID() int32 {
	if x != nil {
		return x.PunishmentID
	}
	return 0
}

type ECMsgGameNumberBombChoosePunishmentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameNumberBombChoosePunishmentRsp) Reset() {
	*x = ECMsgGameNumberBombChoosePunishmentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameNumberBombChoosePunishmentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameNumberBombChoosePunishmentRsp) ProtoMessage() {}

func (x *ECMsgGameNumberBombChoosePunishmentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameNumberBombChoosePunishmentRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameNumberBombChoosePunishmentRsp) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{9}
}

// ECMsgGameNumberBombSetting          = 56 // 数字炸弹-设定
type ECMsgGameNumberBombSettingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxTurn int32 `protobuf:"varint,1,opt,name=MaxTurn,proto3" json:"MaxTurn,omitempty"`
}

func (x *ECMsgGameNumberBombSettingReq) Reset() {
	*x = ECMsgGameNumberBombSettingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameNumberBombSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameNumberBombSettingReq) ProtoMessage() {}

func (x *ECMsgGameNumberBombSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameNumberBombSettingReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameNumberBombSettingReq) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{10}
}

func (x *ECMsgGameNumberBombSettingReq) GetMaxTurn() int32 {
	if x != nil {
		return x.MaxTurn
	}
	return 0
}

type ECMsgGameNumberBombSettingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameNumberBombSettingRsp) Reset() {
	*x = ECMsgGameNumberBombSettingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_number_bomb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameNumberBombSettingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameNumberBombSettingRsp) ProtoMessage() {}

func (x *ECMsgGameNumberBombSettingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_number_bomb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameNumberBombSettingRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameNumberBombSettingRsp) Descriptor() ([]byte, []int) {
	return file_c_room_number_bomb_proto_rawDescGZIP(), []int{11}
}

var File_c_room_number_bomb_proto protoreflect.FileDescriptor

var file_c_room_number_bomb_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x62, 0x6f, 0x6d, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x63, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x18, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42,
	0x6f, 0x6d, 0x62, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x85, 0x04, 0x0a, 0x14,
	0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x65, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x65, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x5d, 0x0a, 0x0f,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x54,
	0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x6f, 0x6d, 0x62, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x42, 0x6f, 0x6d, 0x62, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x75, 0x72, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54,
	0x75, 0x72, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x75, 0x72, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x75, 0x72, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x79, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x53, 0x79, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x66, 0x0a, 0x14, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x6b, 0x0a, 0x25, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65,
	0x50, 0x75, 0x73, 0x68, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x52, 0x6f,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x42, 0x0a, 0x0c,
	0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x4c, 0x0a, 0x2a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x47, 0x75, 0x65, 0x73, 0x73,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x66,
	0x0a, 0x28, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69,
	0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d,
	0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4d, 0x61, 0x78,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3f, 0x0a, 0x1b, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47,
	0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x47, 0x75, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x47, 0x75, 0x65, 0x73,
	0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x1b, 0x45, 0x43, 0x4d, 0x73, 0x67,
	0x47, 0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x47, 0x75,
	0x65, 0x73, 0x73, 0x52, 0x73, 0x70, 0x22, 0x74, 0x0a, 0x22, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47,
	0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d,
	0x62, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a, 0x06,
	0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x61, 0x6c, 0x6b,
	0x65, 0x72, 0x52, 0x06, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x75,
	0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x26,
	0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42,
	0x6f, 0x6d, 0x62, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x50, 0x75, 0x6e, 0x69, 0x73, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x75, 0x6e, 0x69, 0x73, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x50, 0x75,
	0x6e, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x28, 0x0a, 0x26, 0x45, 0x43,
	0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d,
	0x62, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x50, 0x75, 0x6e, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x73, 0x70, 0x22, 0x39, 0x0a, 0x1d, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x75, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x75, 0x72, 0x6e, 0x22,
	0x1f, 0x0a, 0x1d, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x73, 0x70,
	0x2a, 0xa1, 0x01, 0x0a, 0x0f, 0x45, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62,
	0x53, 0x74, 0x65, 0x70, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42,
	0x6f, 0x6d, 0x62, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x00, 0x12, 0x1c,
	0x0a, 0x18, 0x45, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x53, 0x74, 0x65,
	0x70, 0x47, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a,
	0x45, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x53, 0x74, 0x65, 0x70, 0x47,
	0x75, 0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16,
	0x45, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x53, 0x74, 0x65, 0x70, 0x54,
	0x75, 0x72, 0x6e, 0x45, 0x6e, 0x64, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x53, 0x74, 0x65, 0x70, 0x47, 0x61, 0x6d, 0x65, 0x45,
	0x6e, 0x64, 0x10, 0x04, 0x42, 0x1a, 0x5a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x63, 0x65, 0x6c, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c_room_number_bomb_proto_rawDescOnce sync.Once
	file_c_room_number_bomb_proto_rawDescData = file_c_room_number_bomb_proto_rawDesc
)

func file_c_room_number_bomb_proto_rawDescGZIP() []byte {
	file_c_room_number_bomb_proto_rawDescOnce.Do(func() {
		file_c_room_number_bomb_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_room_number_bomb_proto_rawDescData)
	})
	return file_c_room_number_bomb_proto_rawDescData
}

var file_c_room_number_bomb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c_room_number_bomb_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_c_room_number_bomb_proto_goTypes = []interface{}{
	(ENumberBombStep)(0),                               // 0: pbclient.ENumberBombStep
	(*NumberBombPlayerGameData)(nil),                   // 1: pbclient.NumberBombPlayerGameData
	(*RoomNumberBombDetail)(nil),                       // 2: pbclient.RoomNumberBombDetail
	(*ECMsgGamePushNumberBombRoomDataNotify)(nil),      // 3: pbclient.ECMsgGamePushNumberBombRoomDataNotify
	(*ECMsgGamePushNumberBombGuesserChangeNotify)(nil), // 4: pbclient.ECMsgGamePushNumberBombGuesserChangeNotify
	(*ECMsgGamePushNumberBombRangeChangeNotify)(nil),   // 5: pbclient.ECMsgGamePushNumberBombRangeChangeNotify
	(*ECMsgGameNumberBombGuessReq)(nil),                // 6: pbclient.ECMsgGameNumberBombGuessReq
	(*ECMsgGameNumberBombGuessRsp)(nil),                // 7: pbclient.ECMsgGameNumberBombGuessRsp
	(*ECMsgGamePushNumberBombGuessNotify)(nil),         // 8: pbclient.ECMsgGamePushNumberBombGuessNotify
	(*ECMsgGameNumberBombChoosePunishmentReq)(nil),     // 9: pbclient.ECMsgGameNumberBombChoosePunishmentReq
	(*ECMsgGameNumberBombChoosePunishmentRsp)(nil),     // 10: pbclient.ECMsgGameNumberBombChoosePunishmentRsp
	(*ECMsgGameNumberBombSettingReq)(nil),              // 11: pbclient.ECMsgGameNumberBombSettingReq
	(*ECMsgGameNumberBombSettingRsp)(nil),              // 12: pbclient.ECMsgGameNumberBombSettingRsp
	nil,                                                // 13: pbclient.RoomNumberBombDetail.PlayersGameDataEntry
	(*RoomTalker)(nil),                                 // 14: pbclient.RoomTalker
}
var file_c_room_number_bomb_proto_depIdxs = []int32{
	13, // 0: pbclient.RoomNumberBombDetail.PlayersGameData:type_name -> pbclient.RoomNumberBombDetail.PlayersGameDataEntry
	2,  // 1: pbclient.ECMsgGamePushNumberBombRoomDataNotify.RoomGameData:type_name -> pbclient.RoomNumberBombDetail
	14, // 2: pbclient.ECMsgGamePushNumberBombGuessNotify.Talker:type_name -> pbclient.RoomTalker
	1,  // 3: pbclient.RoomNumberBombDetail.PlayersGameDataEntry.value:type_name -> pbclient.NumberBombPlayerGameData
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_c_room_number_bomb_proto_init() }
func file_c_room_number_bomb_proto_init() {
	if File_c_room_number_bomb_proto != nil {
		return
	}
	file_c_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_c_room_number_bomb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberBombPlayerGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomNumberBombDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushNumberBombRoomDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushNumberBombGuesserChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushNumberBombRangeChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameNumberBombGuessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameNumberBombGuessRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushNumberBombGuessNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameNumberBombChoosePunishmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameNumberBombChoosePunishmentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameNumberBombSettingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_number_bomb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameNumberBombSettingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_room_number_bomb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_room_number_bomb_proto_goTypes,
		DependencyIndexes: file_c_room_number_bomb_proto_depIdxs,
		EnumInfos:         file_c_room_number_bomb_proto_enumTypes,
		MessageInfos:      file_c_room_number_bomb_proto_msgTypes,
	}.Build()
	File_c_room_number_bomb_proto = out.File
	file_c_room_number_bomb_proto_rawDesc = nil
	file_c_room_number_bomb_proto_goTypes = nil
	file_c_room_number_bomb_proto_depIdxs = nil
}
