// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_room_running.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 热血奔跑
type ERunningStep int32

const (
	ERunningStep_ERunningStepReady   ERunningStep = 0 // 准备阶段
	ERunningStep_ERunningStepRunning ERunningStep = 1 // 奔跑阶段
	ERunningStep_ERunningStepEnd     ERunningStep = 2 // 结束
)

// Enum value maps for ERunningStep.
var (
	ERunningStep_name = map[int32]string{
		0: "ERunningStepReady",
		1: "ERunningStepRunning",
		2: "ERunningStepEnd",
	}
	ERunningStep_value = map[string]int32{
		"ERunningStepReady":   0,
		"ERunningStepRunning": 1,
		"ERunningStepEnd":     2,
	}
)

func (x ERunningStep) Enum() *ERunningStep {
	p := new(ERunningStep)
	*p = x
	return p
}

func (x ERunningStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERunningStep) Descriptor() protoreflect.EnumDescriptor {
	return file_c_room_running_proto_enumTypes[0].Descriptor()
}

func (ERunningStep) Type() protoreflect.EnumType {
	return &file_c_room_running_proto_enumTypes[0]
}

func (x ERunningStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERunningStep.Descriptor instead.
func (ERunningStep) EnumDescriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{0}
}

// 玩家游戏数据
type RunningPlayerGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`     // 角色id
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`  // 昵称
	Icon     int32  `protobuf:"varint,3,opt,name=Icon,proto3" json:"Icon,omitempty"`         // 图像
	IsOnline bool   `protobuf:"varint,4,opt,name=IsOnline,proto3" json:"IsOnline,omitempty"` // 是否在线
	Ready    int32  `protobuf:"varint,5,opt,name=Ready,proto3" json:"Ready,omitempty"`       // 准备状态 0-未准备 1-准备了
}

func (x *RunningPlayerGameData) Reset() {
	*x = RunningPlayerGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningPlayerGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningPlayerGameData) ProtoMessage() {}

func (x *RunningPlayerGameData) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningPlayerGameData.ProtoReflect.Descriptor instead.
func (*RunningPlayerGameData) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{0}
}

func (x *RunningPlayerGameData) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RunningPlayerGameData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RunningPlayerGameData) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *RunningPlayerGameData) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *RunningPlayerGameData) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

// 房间游戏数据
type RoomRunningDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomStep        int32                            `protobuf:"varint,1,opt,name=RoomStep,proto3" json:"RoomStep,omitempty"`                                                                                                       // 房间游戏阶段 对应 EUndercoverStep
	StepTime        int64                            `protobuf:"varint,2,opt,name=StepTime,proto3" json:"StepTime,omitempty"`                                                                                                       // 阶段对应的开始时间戳
	PlayersGameData map[int64]*RunningPlayerGameData `protobuf:"bytes,3,rep,name=PlayersGameData,proto3" json:"PlayersGameData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 玩家游戏数据
	RankList        []int64                          `protobuf:"varint,4,rep,packed,name=RankList,proto3" json:"RankList,omitempty"`                                                                                                // 排名列表(数组元素为玩家id)
	Distance        int32                            `protobuf:"varint,5,opt,name=Distance,proto3" json:"Distance,omitempty"`                                                                                                       // 距离
	GameTime        int32                            `protobuf:"varint,6,opt,name=GameTime,proto3" json:"GameTime,omitempty"`                                                                                                       // 游戏时间
}

func (x *RoomRunningDetail) Reset() {
	*x = RoomRunningDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRunningDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRunningDetail) ProtoMessage() {}

func (x *RoomRunningDetail) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRunningDetail.ProtoReflect.Descriptor instead.
func (*RoomRunningDetail) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{1}
}

func (x *RoomRunningDetail) GetRoomStep() int32 {
	if x != nil {
		return x.RoomStep
	}
	return 0
}

func (x *RoomRunningDetail) GetStepTime() int64 {
	if x != nil {
		return x.StepTime
	}
	return 0
}

func (x *RoomRunningDetail) GetPlayersGameData() map[int64]*RunningPlayerGameData {
	if x != nil {
		return x.PlayersGameData
	}
	return nil
}

func (x *RoomRunningDetail) GetRankList() []int64 {
	if x != nil {
		return x.RankList
	}
	return nil
}

func (x *RoomRunningDetail) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RoomRunningDetail) GetGameTime() int32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

// ECMsgGamePushRunningRoomData = 90 // 热血奔跑-推送房间游戏数据
type ECMsgGamePushRunningRoomDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomGameData *RoomRunningDetail `protobuf:"bytes,1,opt,name=RoomGameData,proto3" json:"RoomGameData,omitempty"`
}

func (x *ECMsgGamePushRunningRoomDataNotify) Reset() {
	*x = ECMsgGamePushRunningRoomDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRunningRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRunningRoomDataNotify) ProtoMessage() {}

func (x *ECMsgGamePushRunningRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRunningRoomDataNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRunningRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{2}
}

func (x *ECMsgGamePushRunningRoomDataNotify) GetRoomGameData() *RoomRunningDetail {
	if x != nil {
		return x.RoomGameData
	}
	return nil
}

// ECMsgGameRunningSendItem            = 91 // 热血奔跑-发射炸弹
type ECMsgGameRunningSendItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	ItemID int32 `protobuf:"varint,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
}

func (x *ECMsgGameRunningSendItemReq) Reset() {
	*x = ECMsgGameRunningSendItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRunningSendItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRunningSendItemReq) ProtoMessage() {}

func (x *ECMsgGameRunningSendItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRunningSendItemReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameRunningSendItemReq) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{3}
}

func (x *ECMsgGameRunningSendItemReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ECMsgGameRunningSendItemReq) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type ECMsgGameRunningSendItemRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameRunningSendItemRsp) Reset() {
	*x = ECMsgGameRunningSendItemRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRunningSendItemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRunningSendItemRsp) ProtoMessage() {}

func (x *ECMsgGameRunningSendItemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRunningSendItemRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameRunningSendItemRsp) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{4}
}

// ECMsgGamePushRunningSendItem        = 92 // 热血奔跑-推送发射炸弹
type ECMsgGamePushRunningSendItemNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	ItemID int32 `protobuf:"varint,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"` // 道具id
}

func (x *ECMsgGamePushRunningSendItemNotify) Reset() {
	*x = ECMsgGamePushRunningSendItemNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRunningSendItemNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRunningSendItemNotify) ProtoMessage() {}

func (x *ECMsgGamePushRunningSendItemNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRunningSendItemNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRunningSendItemNotify) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{5}
}

func (x *ECMsgGamePushRunningSendItemNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ECMsgGamePushRunningSendItemNotify) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

// ECMsgGameRunningReachEnd            = 93 // 热血奔跑-到达终点
type ECMsgGameRunningReachEndReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameRunningReachEndReq) Reset() {
	*x = ECMsgGameRunningReachEndReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRunningReachEndReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRunningReachEndReq) ProtoMessage() {}

func (x *ECMsgGameRunningReachEndReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRunningReachEndReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameRunningReachEndReq) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{6}
}

type ECMsgGameRunningReachEndRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameRunningReachEndRsp) Reset() {
	*x = ECMsgGameRunningReachEndRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRunningReachEndRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRunningReachEndRsp) ProtoMessage() {}

func (x *ECMsgGameRunningReachEndRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRunningReachEndRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameRunningReachEndRsp) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{7}
}

// ECMsgGamePushRunningReachEnd        = 94 // 热血奔跑-推送有人到达终点了
type ECMsgGamePushRunningReachEndNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *ECMsgGamePushRunningReachEndNotify) Reset() {
	*x = ECMsgGamePushRunningReachEndNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRunningReachEndNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRunningReachEndNotify) ProtoMessage() {}

func (x *ECMsgGamePushRunningReachEndNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRunningReachEndNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRunningReachEndNotify) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{8}
}

func (x *ECMsgGamePushRunningReachEndNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

// ECMsgGameRunningSetting      = 95 // 热血奔跑-游戏设定
type ECMsgGameRunningSettingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance int32 `protobuf:"varint,1,opt,name=Distance,proto3" json:"Distance,omitempty"` // 距离
	GameTime int32 `protobuf:"varint,2,opt,name=GameTime,proto3" json:"GameTime,omitempty"` // 游戏时间
}

func (x *ECMsgGameRunningSettingReq) Reset() {
	*x = ECMsgGameRunningSettingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRunningSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRunningSettingReq) ProtoMessage() {}

func (x *ECMsgGameRunningSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRunningSettingReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameRunningSettingReq) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{9}
}

func (x *ECMsgGameRunningSettingReq) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *ECMsgGameRunningSettingReq) GetGameTime() int32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

type ECMsgGameRunningSettingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameRunningSettingRsp) Reset() {
	*x = ECMsgGameRunningSettingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRunningSettingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRunningSettingRsp) ProtoMessage() {}

func (x *ECMsgGameRunningSettingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRunningSettingRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameRunningSettingRsp) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{10}
}

// ECMsgGamePushRunningSetting  = 96 // 热血奔跑-推送游戏设定
type ECMsgGamePushRunningSettingNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance int32 `protobuf:"varint,1,opt,name=Distance,proto3" json:"Distance,omitempty"` // 距离
	GameTime int32 `protobuf:"varint,2,opt,name=GameTime,proto3" json:"GameTime,omitempty"` // 游戏时间
}

func (x *ECMsgGamePushRunningSettingNotify) Reset() {
	*x = ECMsgGamePushRunningSettingNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_running_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRunningSettingNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRunningSettingNotify) ProtoMessage() {}

func (x *ECMsgGamePushRunningSettingNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_running_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRunningSettingNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRunningSettingNotify) Descriptor() ([]byte, []int) {
	return file_c_room_running_proto_rawDescGZIP(), []int{11}
}

func (x *ECMsgGamePushRunningSettingNotify) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *ECMsgGamePushRunningSettingNotify) GetGameTime() int32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

var File_c_room_running_proto protoreflect.FileDescriptor

var file_c_room_running_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x22, 0x91, 0x01, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x63,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x22, 0xe0, 0x02, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x74, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x62,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x1a, 0x63, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x65, 0x0a, 0x22, 0x45, 0x43, 0x4d, 0x73, 0x67,
	0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x3f, 0x0a,
	0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4d,
	0x0a, 0x1b, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x22, 0x1d, 0x0a,
	0x1b, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x73, 0x70, 0x22, 0x54, 0x0a, 0x22,
	0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x44, 0x22, 0x1d, 0x0a, 0x1b, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x22, 0x1d, 0x0a, 0x1b, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x68, 0x45, 0x6e, 0x64, 0x52, 0x73, 0x70,
	0x22, 0x3c, 0x0a, 0x22, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x68, 0x45, 0x6e, 0x64,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x54,
	0x0a, 0x1a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x73, 0x70, 0x22, 0x5b, 0x0a, 0x21, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x2a,
	0x53, 0x0a, 0x0c, 0x45, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x15, 0x0a, 0x11, 0x45, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x65, 0x70, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x65, 0x70, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x65, 0x70, 0x45,
	0x6e, 0x64, 0x10, 0x02, 0x42, 0x1a, 0x5a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x63, 0x65, 0x6c, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c_room_running_proto_rawDescOnce sync.Once
	file_c_room_running_proto_rawDescData = file_c_room_running_proto_rawDesc
)

func file_c_room_running_proto_rawDescGZIP() []byte {
	file_c_room_running_proto_rawDescOnce.Do(func() {
		file_c_room_running_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_room_running_proto_rawDescData)
	})
	return file_c_room_running_proto_rawDescData
}

var file_c_room_running_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c_room_running_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_c_room_running_proto_goTypes = []interface{}{
	(ERunningStep)(0),                          // 0: pbclient.ERunningStep
	(*RunningPlayerGameData)(nil),              // 1: pbclient.RunningPlayerGameData
	(*RoomRunningDetail)(nil),                  // 2: pbclient.RoomRunningDetail
	(*ECMsgGamePushRunningRoomDataNotify)(nil), // 3: pbclient.ECMsgGamePushRunningRoomDataNotify
	(*ECMsgGameRunningSendItemReq)(nil),        // 4: pbclient.ECMsgGameRunningSendItemReq
	(*ECMsgGameRunningSendItemRsp)(nil),        // 5: pbclient.ECMsgGameRunningSendItemRsp
	(*ECMsgGamePushRunningSendItemNotify)(nil), // 6: pbclient.ECMsgGamePushRunningSendItemNotify
	(*ECMsgGameRunningReachEndReq)(nil),        // 7: pbclient.ECMsgGameRunningReachEndReq
	(*ECMsgGameRunningReachEndRsp)(nil),        // 8: pbclient.ECMsgGameRunningReachEndRsp
	(*ECMsgGamePushRunningReachEndNotify)(nil), // 9: pbclient.ECMsgGamePushRunningReachEndNotify
	(*ECMsgGameRunningSettingReq)(nil),         // 10: pbclient.ECMsgGameRunningSettingReq
	(*ECMsgGameRunningSettingRsp)(nil),         // 11: pbclient.ECMsgGameRunningSettingRsp
	(*ECMsgGamePushRunningSettingNotify)(nil),  // 12: pbclient.ECMsgGamePushRunningSettingNotify
	nil, // 13: pbclient.RoomRunningDetail.PlayersGameDataEntry
}
var file_c_room_running_proto_depIdxs = []int32{
	13, // 0: pbclient.RoomRunningDetail.PlayersGameData:type_name -> pbclient.RoomRunningDetail.PlayersGameDataEntry
	2,  // 1: pbclient.ECMsgGamePushRunningRoomDataNotify.RoomGameData:type_name -> pbclient.RoomRunningDetail
	1,  // 2: pbclient.RoomRunningDetail.PlayersGameDataEntry.value:type_name -> pbclient.RunningPlayerGameData
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_c_room_running_proto_init() }
func file_c_room_running_proto_init() {
	if File_c_room_running_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c_room_running_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningPlayerGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomRunningDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRunningRoomDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRunningSendItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRunningSendItemRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRunningSendItemNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRunningReachEndReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRunningReachEndRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRunningReachEndNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRunningSettingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRunningSettingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_running_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRunningSettingNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_room_running_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_room_running_proto_goTypes,
		DependencyIndexes: file_c_room_running_proto_depIdxs,
		EnumInfos:         file_c_room_running_proto_enumTypes,
		MessageInfos:      file_c_room_running_proto_msgTypes,
	}.Build()
	File_c_room_running_proto = out.File
	file_c_room_running_proto_rawDesc = nil
	file_c_room_running_proto_goTypes = nil
	file_c_room_running_proto_depIdxs = nil
}
