// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_room_undercover.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 谁是卧底
type EUndercoverStep int32

const (
	EUndercoverStep_EUndercoverStepReady       EUndercoverStep = 0 // 准备阶段
	EUndercoverStep_EUndercoverStepGenWords    EUndercoverStep = 1 // 分配词汇
	EUndercoverStep_EUndercoverStepTalk        EUndercoverStep = 2 // 发言阶段
	EUndercoverStep_EUndercoverStepVote        EUndercoverStep = 3 // 投票阶段
	EUndercoverStep_EUndercoverStepVoteSummary EUndercoverStep = 4 // 投票结束汇总阶段
	EUndercoverStep_EUndercoverStepEnd         EUndercoverStep = 5 // 游戏结束阶段
)

// Enum value maps for EUndercoverStep.
var (
	EUndercoverStep_name = map[int32]string{
		0: "EUndercoverStepReady",
		1: "EUndercoverStepGenWords",
		2: "EUndercoverStepTalk",
		3: "EUndercoverStepVote",
		4: "EUndercoverStepVoteSummary",
		5: "EUndercoverStepEnd",
	}
	EUndercoverStep_value = map[string]int32{
		"EUndercoverStepReady":       0,
		"EUndercoverStepGenWords":    1,
		"EUndercoverStepTalk":        2,
		"EUndercoverStepVote":        3,
		"EUndercoverStepVoteSummary": 4,
		"EUndercoverStepEnd":         5,
	}
)

func (x EUndercoverStep) Enum() *EUndercoverStep {
	p := new(EUndercoverStep)
	*p = x
	return p
}

func (x EUndercoverStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EUndercoverStep) Descriptor() protoreflect.EnumDescriptor {
	return file_c_room_undercover_proto_enumTypes[0].Descriptor()
}

func (EUndercoverStep) Type() protoreflect.EnumType {
	return &file_c_room_undercover_proto_enumTypes[0]
}

func (x EUndercoverStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EUndercoverStep.Descriptor instead.
func (EUndercoverStep) EnumDescriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{0}
}

// 玩家游戏数据
type UndercoverPlayerGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID       int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Nickname     string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`          // 昵称
	IsOut        bool   `protobuf:"varint,3,opt,name=IsOut,proto3" json:"IsOut,omitempty"`               // 是否出局
	SelfWords    string `protobuf:"bytes,4,opt,name=SelfWords,proto3" json:"SelfWords,omitempty"`        // 自己的词汇
	IsTalked     bool   `protobuf:"varint,5,opt,name=IsTalked,proto3" json:"IsTalked,omitempty"`         // 本次是否已经发言了
	PlayerNumber int32  `protobuf:"varint,6,opt,name=PlayerNumber,proto3" json:"PlayerNumber,omitempty"` // 玩家编号
	Ready        int32  `protobuf:"varint,7,opt,name=Ready,proto3" json:"Ready,omitempty"`               // 准备状态 0-未准备 1-准备了
	VoteNum      int32  `protobuf:"varint,8,opt,name=VoteNum,proto3" json:"VoteNum,omitempty"`           // 本次得票数
}

func (x *UndercoverPlayerGameData) Reset() {
	*x = UndercoverPlayerGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndercoverPlayerGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndercoverPlayerGameData) ProtoMessage() {}

func (x *UndercoverPlayerGameData) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndercoverPlayerGameData.ProtoReflect.Descriptor instead.
func (*UndercoverPlayerGameData) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{0}
}

func (x *UndercoverPlayerGameData) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *UndercoverPlayerGameData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UndercoverPlayerGameData) GetIsOut() bool {
	if x != nil {
		return x.IsOut
	}
	return false
}

func (x *UndercoverPlayerGameData) GetSelfWords() string {
	if x != nil {
		return x.SelfWords
	}
	return ""
}

func (x *UndercoverPlayerGameData) GetIsTalked() bool {
	if x != nil {
		return x.IsTalked
	}
	return false
}

func (x *UndercoverPlayerGameData) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

func (x *UndercoverPlayerGameData) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *UndercoverPlayerGameData) GetVoteNum() int32 {
	if x != nil {
		return x.VoteNum
	}
	return 0
}

// 房间游戏数据
type RoomUndercoverDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomStep        int32                               `protobuf:"varint,1,opt,name=RoomStep,proto3" json:"RoomStep,omitempty"`                                                                                                       // 房间游戏阶段 对应 EUndercoverStep
	StepTime        int64                               `protobuf:"varint,2,opt,name=StepTime,proto3" json:"StepTime,omitempty"`                                                                                                       // 阶段对应的开始时间戳
	PlayersGameData map[int64]*UndercoverPlayerGameData `protobuf:"bytes,3,rep,name=PlayersGameData,proto3" json:"PlayersGameData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 玩家游戏数据
	TalkRoleID      int64                               `protobuf:"varint,4,opt,name=TalkRoleID,proto3" json:"TalkRoleID,omitempty"`                                                                                                   // 当前发言玩家
	TalkRoleNumber  int32                               `protobuf:"varint,5,opt,name=TalkRoleNumber,proto3" json:"TalkRoleNumber,omitempty"`                                                                                           // 当前发言玩家编号
	UnderWin        bool                                `protobuf:"varint,6,opt,name=UnderWin,proto3" json:"UnderWin,omitempty"`                                                                                                       // 卧底是否胜利 false失败 true胜利
}

func (x *RoomUndercoverDetail) Reset() {
	*x = RoomUndercoverDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomUndercoverDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUndercoverDetail) ProtoMessage() {}

func (x *RoomUndercoverDetail) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUndercoverDetail.ProtoReflect.Descriptor instead.
func (*RoomUndercoverDetail) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{1}
}

func (x *RoomUndercoverDetail) GetRoomStep() int32 {
	if x != nil {
		return x.RoomStep
	}
	return 0
}

func (x *RoomUndercoverDetail) GetStepTime() int64 {
	if x != nil {
		return x.StepTime
	}
	return 0
}

func (x *RoomUndercoverDetail) GetPlayersGameData() map[int64]*UndercoverPlayerGameData {
	if x != nil {
		return x.PlayersGameData
	}
	return nil
}

func (x *RoomUndercoverDetail) GetTalkRoleID() int64 {
	if x != nil {
		return x.TalkRoleID
	}
	return 0
}

func (x *RoomUndercoverDetail) GetTalkRoleNumber() int32 {
	if x != nil {
		return x.TalkRoleNumber
	}
	return 0
}

func (x *RoomUndercoverDetail) GetUnderWin() bool {
	if x != nil {
		return x.UnderWin
	}
	return false
}

// ECMsgGamePushUndercoverRoomData     = 30 // 谁是卧底-推送房间游戏数据
type ECMsgGamePushUndercoverRoomDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomGameData *RoomUndercoverDetail `protobuf:"bytes,1,opt,name=RoomGameData,proto3" json:"RoomGameData,omitempty"`
}

func (x *ECMsgGamePushUndercoverRoomDataNotify) Reset() {
	*x = ECMsgGamePushUndercoverRoomDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushUndercoverRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushUndercoverRoomDataNotify) ProtoMessage() {}

func (x *ECMsgGamePushUndercoverRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushUndercoverRoomDataNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushUndercoverRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{2}
}

func (x *ECMsgGamePushUndercoverRoomDataNotify) GetRoomGameData() *RoomUndercoverDetail {
	if x != nil {
		return x.RoomGameData
	}
	return nil
}

// ECMsgGamePushPlayerUnderWords       = 31 // 谁是卧底-推送玩家卧底词汇更新
type ECMsgGamePushPlayerUnderWordsNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerWords map[int64]string `protobuf:"bytes,1,rep,name=PlayerWords,proto3" json:"PlayerWords,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ECMsgGamePushPlayerUnderWordsNotify) Reset() {
	*x = ECMsgGamePushPlayerUnderWordsNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushPlayerUnderWordsNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushPlayerUnderWordsNotify) ProtoMessage() {}

func (x *ECMsgGamePushPlayerUnderWordsNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushPlayerUnderWordsNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushPlayerUnderWordsNotify) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{3}
}

func (x *ECMsgGamePushPlayerUnderWordsNotify) GetPlayerWords() map[int64]string {
	if x != nil {
		return x.PlayerWords
	}
	return nil
}

// ECMsgGameUndercoverVote             = 32 // 谁是卧底-投票
type ECMsgGameUndercoverVoteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetRoleID int64 `protobuf:"varint,1,opt,name=TargetRoleID,proto3" json:"TargetRoleID,omitempty"` // 要投票的玩家
}

func (x *ECMsgGameUndercoverVoteReq) Reset() {
	*x = ECMsgGameUndercoverVoteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameUndercoverVoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameUndercoverVoteReq) ProtoMessage() {}

func (x *ECMsgGameUndercoverVoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameUndercoverVoteReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameUndercoverVoteReq) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{4}
}

func (x *ECMsgGameUndercoverVoteReq) GetTargetRoleID() int64 {
	if x != nil {
		return x.TargetRoleID
	}
	return 0
}

type ECMsgGameUndercoverVoteRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameUndercoverVoteRsp) Reset() {
	*x = ECMsgGameUndercoverVoteRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameUndercoverVoteRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameUndercoverVoteRsp) ProtoMessage() {}

func (x *ECMsgGameUndercoverVoteRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameUndercoverVoteRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameUndercoverVoteRsp) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{5}
}

// ECMsgGamePushUndercoverTalkerChange = 33 // 谁是卧底-发言人变更
type ECMsgGamePushUndercoverTalkerChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkRoleID int64 `protobuf:"varint,1,opt,name=TalkRoleID,proto3" json:"TalkRoleID,omitempty"`
}

func (x *ECMsgGamePushUndercoverTalkerChangeNotify) Reset() {
	*x = ECMsgGamePushUndercoverTalkerChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushUndercoverTalkerChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushUndercoverTalkerChangeNotify) ProtoMessage() {}

func (x *ECMsgGamePushUndercoverTalkerChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushUndercoverTalkerChangeNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushUndercoverTalkerChangeNotify) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{6}
}

func (x *ECMsgGamePushUndercoverTalkerChangeNotify) GetTalkRoleID() int64 {
	if x != nil {
		return x.TalkRoleID
	}
	return 0
}

// ECMsgGamePushUndercoverVote         = 34 // 谁是卧底-推送投票
type ECMsgGamePushUndercoverVoteNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID       int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`             // 投票发起人
	TargetRoleID int64 `protobuf:"varint,2,opt,name=TargetRoleID,proto3" json:"TargetRoleID,omitempty"` // 被投票的人
}

func (x *ECMsgGamePushUndercoverVoteNotify) Reset() {
	*x = ECMsgGamePushUndercoverVoteNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushUndercoverVoteNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushUndercoverVoteNotify) ProtoMessage() {}

func (x *ECMsgGamePushUndercoverVoteNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushUndercoverVoteNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushUndercoverVoteNotify) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{7}
}

func (x *ECMsgGamePushUndercoverVoteNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ECMsgGamePushUndercoverVoteNotify) GetTargetRoleID() int64 {
	if x != nil {
		return x.TargetRoleID
	}
	return 0
}

// ECMsgGamePushUndercoverOut          = 35 // 谁是卧底-推送玩家出局
type ECMsgGamePushUndercoverOutNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"` // 出局的人
}

func (x *ECMsgGamePushUndercoverOutNotify) Reset() {
	*x = ECMsgGamePushUndercoverOutNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushUndercoverOutNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushUndercoverOutNotify) ProtoMessage() {}

func (x *ECMsgGamePushUndercoverOutNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushUndercoverOutNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushUndercoverOutNotify) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{8}
}

func (x *ECMsgGamePushUndercoverOutNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

// ECMsgGameUndercoverTalk             = 36 // 谁是卧底-发言
type ECMsgGameUndercoverTalkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkContent string `protobuf:"bytes,1,opt,name=TalkContent,proto3" json:"TalkContent,omitempty"` // 发言内容
}

func (x *ECMsgGameUndercoverTalkReq) Reset() {
	*x = ECMsgGameUndercoverTalkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameUndercoverTalkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameUndercoverTalkReq) ProtoMessage() {}

func (x *ECMsgGameUndercoverTalkReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameUndercoverTalkReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameUndercoverTalkReq) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{9}
}

func (x *ECMsgGameUndercoverTalkReq) GetTalkContent() string {
	if x != nil {
		return x.TalkContent
	}
	return ""
}

type ECMsgGameUndercoverTalkRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameUndercoverTalkRsp) Reset() {
	*x = ECMsgGameUndercoverTalkRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameUndercoverTalkRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameUndercoverTalkRsp) ProtoMessage() {}

func (x *ECMsgGameUndercoverTalkRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameUndercoverTalkRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameUndercoverTalkRsp) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{10}
}

// ECMsgGamePushUndercoverTalk         = 37 // 谁是卧底-推送发言
type ECMsgGamePushUndercoverTalkNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Talker       *RoomTalker `protobuf:"bytes,1,opt,name=Talker,proto3" json:"Talker,omitempty"`              // 说话的人
	TalkContent  string      `protobuf:"bytes,2,opt,name=TalkContent,proto3" json:"TalkContent,omitempty"`    // 聊天内容
	PlayerNumber int32       `protobuf:"varint,3,opt,name=PlayerNumber,proto3" json:"PlayerNumber,omitempty"` // 玩家编号
}

func (x *ECMsgGamePushUndercoverTalkNotify) Reset() {
	*x = ECMsgGamePushUndercoverTalkNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_undercover_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushUndercoverTalkNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushUndercoverTalkNotify) ProtoMessage() {}

func (x *ECMsgGamePushUndercoverTalkNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_undercover_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushUndercoverTalkNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushUndercoverTalkNotify) Descriptor() ([]byte, []int) {
	return file_c_room_undercover_proto_rawDescGZIP(), []int{11}
}

func (x *ECMsgGamePushUndercoverTalkNotify) GetTalker() *RoomTalker {
	if x != nil {
		return x.Talker
	}
	return nil
}

func (x *ECMsgGamePushUndercoverTalkNotify) GetTalkContent() string {
	if x != nil {
		return x.TalkContent
	}
	return ""
}

func (x *ECMsgGamePushUndercoverTalkNotify) GetPlayerNumber() int32 {
	if x != nil {
		return x.PlayerNumber
	}
	return 0
}

var File_c_room_undercover_proto protoreflect.FileDescriptor

var file_c_room_undercover_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x63, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x01, 0x0a, 0x18, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x4f, 0x75, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x6c, 0x66, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x65, 0x6c, 0x66, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x54, 0x61,
	0x6c, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x54, 0x61,
	0x6c, 0x6b, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x56, 0x6f, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0xf9, 0x02, 0x0a, 0x14, 0x52, 0x6f, 0x6f,
	0x6d, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x65, 0x70, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x5d, 0x0a, 0x0f, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6b,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x61,
	0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x61, 0x6c, 0x6b,
	0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x1a, 0x66, 0x0a, 0x14,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x6b, 0x0a, 0x25, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x42, 0x0a,
	0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x22, 0xc7, 0x01, 0x0a, 0x23, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50,
	0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x60, 0x0a, 0x0b, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e,
	0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47,
	0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x64,
	0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x1a, 0x45,
	0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x1c, 0x0a,
	0x1a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x29, 0x45,
	0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x55, 0x6e, 0x64, 0x65,
	0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6b,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x61,
	0x6c, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x21, 0x45, 0x43, 0x4d, 0x73,
	0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x56, 0x6f, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x20, 0x45, 0x43, 0x4d,
	0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x1a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61,
	0x6d, 0x65, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x61, 0x6c, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61,
	0x6d, 0x65, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x61, 0x6c, 0x6b,
	0x52, 0x73, 0x70, 0x22, 0x97, 0x01, 0x0a, 0x21, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54,
	0x61, 0x6c, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a, 0x06, 0x54, 0x61, 0x6c,
	0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x52,
	0x06, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x61,
	0x6c, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2a, 0xb2, 0x01,
	0x0a, 0x0f, 0x45, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x65,
	0x70, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x45,
	0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x47, 0x65,
	0x6e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x55, 0x6e, 0x64,
	0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x54, 0x61, 0x6c, 0x6b, 0x10,
	0x02, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x65, 0x70, 0x56, 0x6f, 0x74, 0x65, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x55,
	0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x56, 0x6f, 0x74,
	0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x55,
	0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x45, 0x6e, 0x64,
	0x10, 0x05, 0x42, 0x1a, 0x5a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c_room_undercover_proto_rawDescOnce sync.Once
	file_c_room_undercover_proto_rawDescData = file_c_room_undercover_proto_rawDesc
)

func file_c_room_undercover_proto_rawDescGZIP() []byte {
	file_c_room_undercover_proto_rawDescOnce.Do(func() {
		file_c_room_undercover_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_room_undercover_proto_rawDescData)
	})
	return file_c_room_undercover_proto_rawDescData
}

var file_c_room_undercover_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c_room_undercover_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_c_room_undercover_proto_goTypes = []interface{}{
	(EUndercoverStep)(0),                              // 0: pbclient.EUndercoverStep
	(*UndercoverPlayerGameData)(nil),                  // 1: pbclient.UndercoverPlayerGameData
	(*RoomUndercoverDetail)(nil),                      // 2: pbclient.RoomUndercoverDetail
	(*ECMsgGamePushUndercoverRoomDataNotify)(nil),     // 3: pbclient.ECMsgGamePushUndercoverRoomDataNotify
	(*ECMsgGamePushPlayerUnderWordsNotify)(nil),       // 4: pbclient.ECMsgGamePushPlayerUnderWordsNotify
	(*ECMsgGameUndercoverVoteReq)(nil),                // 5: pbclient.ECMsgGameUndercoverVoteReq
	(*ECMsgGameUndercoverVoteRsp)(nil),                // 6: pbclient.ECMsgGameUndercoverVoteRsp
	(*ECMsgGamePushUndercoverTalkerChangeNotify)(nil), // 7: pbclient.ECMsgGamePushUndercoverTalkerChangeNotify
	(*ECMsgGamePushUndercoverVoteNotify)(nil),         // 8: pbclient.ECMsgGamePushUndercoverVoteNotify
	(*ECMsgGamePushUndercoverOutNotify)(nil),          // 9: pbclient.ECMsgGamePushUndercoverOutNotify
	(*ECMsgGameUndercoverTalkReq)(nil),                // 10: pbclient.ECMsgGameUndercoverTalkReq
	(*ECMsgGameUndercoverTalkRsp)(nil),                // 11: pbclient.ECMsgGameUndercoverTalkRsp
	(*ECMsgGamePushUndercoverTalkNotify)(nil),         // 12: pbclient.ECMsgGamePushUndercoverTalkNotify
	nil,                // 13: pbclient.RoomUndercoverDetail.PlayersGameDataEntry
	nil,                // 14: pbclient.ECMsgGamePushPlayerUnderWordsNotify.PlayerWordsEntry
	(*RoomTalker)(nil), // 15: pbclient.RoomTalker
}
var file_c_room_undercover_proto_depIdxs = []int32{
	13, // 0: pbclient.RoomUndercoverDetail.PlayersGameData:type_name -> pbclient.RoomUndercoverDetail.PlayersGameDataEntry
	2,  // 1: pbclient.ECMsgGamePushUndercoverRoomDataNotify.RoomGameData:type_name -> pbclient.RoomUndercoverDetail
	14, // 2: pbclient.ECMsgGamePushPlayerUnderWordsNotify.PlayerWords:type_name -> pbclient.ECMsgGamePushPlayerUnderWordsNotify.PlayerWordsEntry
	15, // 3: pbclient.ECMsgGamePushUndercoverTalkNotify.Talker:type_name -> pbclient.RoomTalker
	1,  // 4: pbclient.RoomUndercoverDetail.PlayersGameDataEntry.value:type_name -> pbclient.UndercoverPlayerGameData
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_c_room_undercover_proto_init() }
func file_c_room_undercover_proto_init() {
	if File_c_room_undercover_proto != nil {
		return
	}
	file_c_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_c_room_undercover_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndercoverPlayerGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomUndercoverDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushUndercoverRoomDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushPlayerUnderWordsNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameUndercoverVoteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameUndercoverVoteRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushUndercoverTalkerChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushUndercoverVoteNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushUndercoverOutNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameUndercoverTalkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameUndercoverTalkRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_undercover_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushUndercoverTalkNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_room_undercover_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_room_undercover_proto_goTypes,
		DependencyIndexes: file_c_room_undercover_proto_depIdxs,
		EnumInfos:         file_c_room_undercover_proto_enumTypes,
		MessageInfos:      file_c_room_undercover_proto_msgTypes,
	}.Build()
	File_c_room_undercover_proto = out.File
	file_c_room_undercover_proto_rawDesc = nil
	file_c_room_undercover_proto_goTypes = nil
	file_c_room_undercover_proto_depIdxs = nil
}
