// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_room_rescue.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 谁是卧底
type ERescueStep int32

const (
	ERescueStep_ERescueStepReady   ERescueStep = 0 // 准备阶段
	ERescueStep_ERescueStepRunning ERescueStep = 1 // 奔跑阶段
	ERescueStep_ERescueStepEnd     ERescueStep = 2 // 结束
)

// Enum value maps for ERescueStep.
var (
	ERescueStep_name = map[int32]string{
		0: "ERescueStepReady",
		1: "ERescueStepRunning",
		2: "ERescueStepEnd",
	}
	ERescueStep_value = map[string]int32{
		"ERescueStepReady":   0,
		"ERescueStepRunning": 1,
		"ERescueStepEnd":     2,
	}
)

func (x ERescueStep) Enum() *ERescueStep {
	p := new(ERescueStep)
	*p = x
	return p
}

func (x ERescueStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERescueStep) Descriptor() protoreflect.EnumDescriptor {
	return file_c_room_rescue_proto_enumTypes[0].Descriptor()
}

func (ERescueStep) Type() protoreflect.EnumType {
	return &file_c_room_rescue_proto_enumTypes[0]
}

func (x ERescueStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERescueStep.Descriptor instead.
func (ERescueStep) EnumDescriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{0}
}

// 玩家游戏数据
type RescuePlayerGameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`     // 角色id
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`  // 昵称
	Icon     int32  `protobuf:"varint,3,opt,name=Icon,proto3" json:"Icon,omitempty"`         // 图像
	IsOnline bool   `protobuf:"varint,4,opt,name=IsOnline,proto3" json:"IsOnline,omitempty"` // 是否在线
	Ready    int32  `protobuf:"varint,5,opt,name=Ready,proto3" json:"Ready,omitempty"`       // 准备状态 0-未准备 1-准备了
	Hp       int32  `protobuf:"varint,6,opt,name=Hp,proto3" json:"Hp,omitempty"`             // 玩家hp
}

func (x *RescuePlayerGameData) Reset() {
	*x = RescuePlayerGameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RescuePlayerGameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescuePlayerGameData) ProtoMessage() {}

func (x *RescuePlayerGameData) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescuePlayerGameData.ProtoReflect.Descriptor instead.
func (*RescuePlayerGameData) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{0}
}

func (x *RescuePlayerGameData) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RescuePlayerGameData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RescuePlayerGameData) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *RescuePlayerGameData) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *RescuePlayerGameData) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *RescuePlayerGameData) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

// 房间游戏数据
type RoomRescueDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomStep        int32                           `protobuf:"varint,1,opt,name=RoomStep,proto3" json:"RoomStep,omitempty"`                                                                                                       // 房间游戏阶段 对应 EUndercoverStep
	StepTime        int64                           `protobuf:"varint,2,opt,name=StepTime,proto3" json:"StepTime,omitempty"`                                                                                                       // 阶段对应的开始时间戳
	PlayersGameData map[int64]*RescuePlayerGameData `protobuf:"bytes,3,rep,name=PlayersGameData,proto3" json:"PlayersGameData,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 玩家游戏数据
	MaxTime         int32                           `protobuf:"varint,4,opt,name=MaxTime,proto3" json:"MaxTime,omitempty"`
	MaxHp           int32                           `protobuf:"varint,5,opt,name=MaxHp,proto3" json:"MaxHp,omitempty"`
	RankList        []int64                         `protobuf:"varint,6,rep,packed,name=RankList,proto3" json:"RankList,omitempty"` // 排名列表(数组元素为玩家id)
}

func (x *RoomRescueDetail) Reset() {
	*x = RoomRescueDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRescueDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRescueDetail) ProtoMessage() {}

func (x *RoomRescueDetail) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRescueDetail.ProtoReflect.Descriptor instead.
func (*RoomRescueDetail) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{1}
}

func (x *RoomRescueDetail) GetRoomStep() int32 {
	if x != nil {
		return x.RoomStep
	}
	return 0
}

func (x *RoomRescueDetail) GetStepTime() int64 {
	if x != nil {
		return x.StepTime
	}
	return 0
}

func (x *RoomRescueDetail) GetPlayersGameData() map[int64]*RescuePlayerGameData {
	if x != nil {
		return x.PlayersGameData
	}
	return nil
}

func (x *RoomRescueDetail) GetMaxTime() int32 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

func (x *RoomRescueDetail) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *RoomRescueDetail) GetRankList() []int64 {
	if x != nil {
		return x.RankList
	}
	return nil
}

// ECMsgGameRescueSetting      = 70 // 拯救玩家-设定
type ECMsgGameRescueSettingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxTime int32 `protobuf:"varint,1,opt,name=MaxTime,proto3" json:"MaxTime,omitempty"` // 最大时间(秒)
	MaxHp   int32 `protobuf:"varint,2,opt,name=MaxHp,proto3" json:"MaxHp,omitempty"`     // 最大血量设定
}

func (x *ECMsgGameRescueSettingReq) Reset() {
	*x = ECMsgGameRescueSettingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRescueSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRescueSettingReq) ProtoMessage() {}

func (x *ECMsgGameRescueSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRescueSettingReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameRescueSettingReq) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{2}
}

func (x *ECMsgGameRescueSettingReq) GetMaxTime() int32 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

func (x *ECMsgGameRescueSettingReq) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

type ECMsgGameRescueSettingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameRescueSettingRsp) Reset() {
	*x = ECMsgGameRescueSettingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRescueSettingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRescueSettingRsp) ProtoMessage() {}

func (x *ECMsgGameRescueSettingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRescueSettingRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameRescueSettingRsp) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{3}
}

// ECMsgGamePushRescueRoomData = 71 // 数字炸弹-推送房间游戏数据
type ECMsgGamePushRescueRoomDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomGameData *RoomRescueDetail `protobuf:"bytes,1,opt,name=RoomGameData,proto3" json:"RoomGameData,omitempty"`
}

func (x *ECMsgGamePushRescueRoomDataNotify) Reset() {
	*x = ECMsgGamePushRescueRoomDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRescueRoomDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRescueRoomDataNotify) ProtoMessage() {}

func (x *ECMsgGamePushRescueRoomDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRescueRoomDataNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRescueRoomDataNotify) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{4}
}

func (x *ECMsgGamePushRescueRoomDataNotify) GetRoomGameData() *RoomRescueDetail {
	if x != nil {
		return x.RoomGameData
	}
	return nil
}

// ECMsgGamePushRescueSetting  = 72 // 拯救玩家-设定推送
type ECMsgGamePushRescueSettingNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxHp   int32 `protobuf:"varint,1,opt,name=MaxHp,proto3" json:"MaxHp,omitempty"`
	MaxTime int32 `protobuf:"varint,2,opt,name=MaxTime,proto3" json:"MaxTime,omitempty"`
}

func (x *ECMsgGamePushRescueSettingNotify) Reset() {
	*x = ECMsgGamePushRescueSettingNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRescueSettingNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRescueSettingNotify) ProtoMessage() {}

func (x *ECMsgGamePushRescueSettingNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRescueSettingNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRescueSettingNotify) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{5}
}

func (x *ECMsgGamePushRescueSettingNotify) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *ECMsgGamePushRescueSettingNotify) GetMaxTime() int32 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

// ECMsgGameRescueRecvGift     = 73 // 拯救玩家-收到礼物
type ECMsgGameRescueRecvGiftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	ItemID int32 `protobuf:"varint,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"` // 道具ID
}

func (x *ECMsgGameRescueRecvGiftReq) Reset() {
	*x = ECMsgGameRescueRecvGiftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRescueRecvGiftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRescueRecvGiftReq) ProtoMessage() {}

func (x *ECMsgGameRescueRecvGiftReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRescueRecvGiftReq.ProtoReflect.Descriptor instead.
func (*ECMsgGameRescueRecvGiftReq) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{6}
}

func (x *ECMsgGameRescueRecvGiftReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ECMsgGameRescueRecvGiftReq) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type ECMsgGameRescueRecvGiftRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgGameRescueRecvGiftRsp) Reset() {
	*x = ECMsgGameRescueRecvGiftRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGameRescueRecvGiftRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGameRescueRecvGiftRsp) ProtoMessage() {}

func (x *ECMsgGameRescueRecvGiftRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGameRescueRecvGiftRsp.ProtoReflect.Descriptor instead.
func (*ECMsgGameRescueRecvGiftRsp) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{7}
}

// ECMsgGamePushRescueRecvGift = 74 // 拯救玩家-收到礼物推送
type ECMsgGamePushRescueRecvGiftNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	ItemID int32 `protobuf:"varint,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"` // 道具ID
}

func (x *ECMsgGamePushRescueRecvGiftNotify) Reset() {
	*x = ECMsgGamePushRescueRecvGiftNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_rescue_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgGamePushRescueRecvGiftNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgGamePushRescueRecvGiftNotify) ProtoMessage() {}

func (x *ECMsgGamePushRescueRecvGiftNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_rescue_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgGamePushRescueRecvGiftNotify.ProtoReflect.Descriptor instead.
func (*ECMsgGamePushRescueRecvGiftNotify) Descriptor() ([]byte, []int) {
	return file_c_room_rescue_proto_rawDescGZIP(), []int{8}
}

func (x *ECMsgGamePushRescueRecvGiftNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ECMsgGamePushRescueRecvGiftNotify) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

var File_c_room_rescue_proto protoreflect.FileDescriptor

var file_c_room_rescue_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x63, 0x75, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22,
	0xa0, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x48, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x48, 0x70, 0x22, 0xd5, 0x02, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x63, 0x75,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x74, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x59, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61,
	0x78, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x78, 0x48, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x61, 0x78, 0x48, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x61,
	0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x52, 0x61,
	0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x62, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x63, 0x75,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4b, 0x0a, 0x19, 0x45, 0x43,
	0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x78, 0x48, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4d, 0x61, 0x78, 0x48, 0x70, 0x22, 0x1b, 0x0a, 0x19, 0x45, 0x43, 0x4d, 0x73, 0x67,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x73, 0x70, 0x22, 0x63, 0x0a, 0x21, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x3e, 0x0a, 0x0c, 0x52, 0x6f, 0x6f,
	0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x63, 0x75, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x52, 0x6f, 0x6f,
	0x6d, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x20, 0x45, 0x43, 0x4d,
	0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x4d, 0x61, 0x78, 0x48, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x61,
	0x78, 0x48, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4c, 0x0a,
	0x1a, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65,
	0x52, 0x65, 0x63, 0x76, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x22, 0x1c, 0x0a, 0x1a, 0x45,
	0x43, 0x4d, 0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x52, 0x65,
	0x63, 0x76, 0x47, 0x69, 0x66, 0x74, 0x52, 0x73, 0x70, 0x22, 0x53, 0x0a, 0x21, 0x45, 0x43, 0x4d,
	0x73, 0x67, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65,
	0x52, 0x65, 0x63, 0x76, 0x47, 0x69, 0x66, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x2a, 0x4f,
	0x0a, 0x0b, 0x45, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x53, 0x74, 0x65, 0x70, 0x12, 0x14, 0x0a,
	0x10, 0x45, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x53, 0x74,
	0x65, 0x70, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45,
	0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x53, 0x74, 0x65, 0x70, 0x45, 0x6e, 0x64, 0x10, 0x02, 0x42,
	0x1a, 0x5a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_c_room_rescue_proto_rawDescOnce sync.Once
	file_c_room_rescue_proto_rawDescData = file_c_room_rescue_proto_rawDesc
)

func file_c_room_rescue_proto_rawDescGZIP() []byte {
	file_c_room_rescue_proto_rawDescOnce.Do(func() {
		file_c_room_rescue_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_room_rescue_proto_rawDescData)
	})
	return file_c_room_rescue_proto_rawDescData
}

var file_c_room_rescue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c_room_rescue_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_c_room_rescue_proto_goTypes = []interface{}{
	(ERescueStep)(0),                          // 0: pbclient.ERescueStep
	(*RescuePlayerGameData)(nil),              // 1: pbclient.RescuePlayerGameData
	(*RoomRescueDetail)(nil),                  // 2: pbclient.RoomRescueDetail
	(*ECMsgGameRescueSettingReq)(nil),         // 3: pbclient.ECMsgGameRescueSettingReq
	(*ECMsgGameRescueSettingRsp)(nil),         // 4: pbclient.ECMsgGameRescueSettingRsp
	(*ECMsgGamePushRescueRoomDataNotify)(nil), // 5: pbclient.ECMsgGamePushRescueRoomDataNotify
	(*ECMsgGamePushRescueSettingNotify)(nil),  // 6: pbclient.ECMsgGamePushRescueSettingNotify
	(*ECMsgGameRescueRecvGiftReq)(nil),        // 7: pbclient.ECMsgGameRescueRecvGiftReq
	(*ECMsgGameRescueRecvGiftRsp)(nil),        // 8: pbclient.ECMsgGameRescueRecvGiftRsp
	(*ECMsgGamePushRescueRecvGiftNotify)(nil), // 9: pbclient.ECMsgGamePushRescueRecvGiftNotify
	nil, // 10: pbclient.RoomRescueDetail.PlayersGameDataEntry
}
var file_c_room_rescue_proto_depIdxs = []int32{
	10, // 0: pbclient.RoomRescueDetail.PlayersGameData:type_name -> pbclient.RoomRescueDetail.PlayersGameDataEntry
	2,  // 1: pbclient.ECMsgGamePushRescueRoomDataNotify.RoomGameData:type_name -> pbclient.RoomRescueDetail
	1,  // 2: pbclient.RoomRescueDetail.PlayersGameDataEntry.value:type_name -> pbclient.RescuePlayerGameData
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_c_room_rescue_proto_init() }
func file_c_room_rescue_proto_init() {
	if File_c_room_rescue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c_room_rescue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RescuePlayerGameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomRescueDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRescueSettingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRescueSettingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRescueRoomDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRescueSettingNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRescueRecvGiftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGameRescueRecvGiftRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_rescue_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgGamePushRescueRecvGiftNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_room_rescue_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_room_rescue_proto_goTypes,
		DependencyIndexes: file_c_room_rescue_proto_depIdxs,
		EnumInfos:         file_c_room_rescue_proto_enumTypes,
		MessageInfos:      file_c_room_rescue_proto_msgTypes,
	}.Build()
	File_c_room_rescue_proto = out.File
	file_c_room_rescue_proto_rawDesc = nil
	file_c_room_rescue_proto_goTypes = nil
	file_c_room_rescue_proto_depIdxs = nil
}
