// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_room.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 房间摘要
type RoomSimple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID    int64 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"` // 房间ID
	ZoneID    int32 `protobuf:"varint,2,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	NodeIndex int32 `protobuf:"varint,3,opt,name=NodeIndex,proto3" json:"NodeIndex,omitempty"`
}

func (x *RoomSimple) Reset() {
	*x = RoomSimple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSimple) ProtoMessage() {}

func (x *RoomSimple) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSimple.ProtoReflect.Descriptor instead.
func (*RoomSimple) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomSimple) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *RoomSimple) GetZoneID() int32 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *RoomSimple) GetNodeIndex() int32 {
	if x != nil {
		return x.NodeIndex
	}
	return 0
}

// 房间玩家
type RoomPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Icon     int32  `protobuf:"varint,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Ready    int32  `protobuf:"varint,4,opt,name=Ready,proto3" json:"Ready,omitempty"` // 准备状态 0-未准备 1-准备了
}

func (x *RoomPlayer) Reset() {
	*x = RoomPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayer) ProtoMessage() {}

func (x *RoomPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayer.ProtoReflect.Descriptor instead.
func (*RoomPlayer) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomPlayer) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RoomPlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomPlayer) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *RoomPlayer) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

// 房间信息
type RoomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID             int64                 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	GameType           int32                 `protobuf:"varint,2,opt,name=GameType,proto3" json:"GameType,omitempty"`                    // 游戏房间类型
	Players            []*RoomPlayer         `protobuf:"bytes,3,rep,name=Players,proto3" json:"Players,omitempty"`                       // 当前玩家列表
	DrawRoomData       *RoomDrawDetail       `protobuf:"bytes,4,opt,name=DrawRoomData,proto3" json:"DrawRoomData,omitempty"`             // 你画我猜房间游戏数据
	MasterID           int64                 `protobuf:"varint,5,opt,name=MasterID,proto3" json:"MasterID,omitempty"`                    // 房主ID
	UndercoverRoomData *RoomUndercoverDetail `protobuf:"bytes,6,opt,name=UndercoverRoomData,proto3" json:"UndercoverRoomData,omitempty"` // 谁是卧底-房间游戏数据
	NumberbombRoomData *RoomNumberBombDetail `protobuf:"bytes,7,opt,name=NumberbombRoomData,proto3" json:"NumberbombRoomData,omitempty"` // 数字炸弹-房间游戏数据
	RescueRoomData     *RoomRescueDetail     `protobuf:"bytes,8,opt,name=RescueRoomData,proto3" json:"RescueRoomData,omitempty"`         // 拯救玩家-房间游戏数据
	RunningRoomData    *RoomRunningDetail    `protobuf:"bytes,9,opt,name=RunningRoomData,proto3" json:"RunningRoomData,omitempty"`       // 热血奔跑-房间游戏数据
}

func (x *RoomData) Reset() {
	*x = RoomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData) ProtoMessage() {}

func (x *RoomData) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData.ProtoReflect.Descriptor instead.
func (*RoomData) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomData) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *RoomData) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

func (x *RoomData) GetPlayers() []*RoomPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomData) GetDrawRoomData() *RoomDrawDetail {
	if x != nil {
		return x.DrawRoomData
	}
	return nil
}

func (x *RoomData) GetMasterID() int64 {
	if x != nil {
		return x.MasterID
	}
	return 0
}

func (x *RoomData) GetUndercoverRoomData() *RoomUndercoverDetail {
	if x != nil {
		return x.UndercoverRoomData
	}
	return nil
}

func (x *RoomData) GetNumberbombRoomData() *RoomNumberBombDetail {
	if x != nil {
		return x.NumberbombRoomData
	}
	return nil
}

func (x *RoomData) GetRescueRoomData() *RoomRescueDetail {
	if x != nil {
		return x.RescueRoomData
	}
	return nil
}

func (x *RoomData) GetRunningRoomData() *RoomRunningDetail {
	if x != nil {
		return x.RunningRoomData
	}
	return nil
}

// ECMsgRoomCreate = 1 // 创建房间
type ECMsgRoomCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameType int32 `protobuf:"varint,1,opt,name=GameType,proto3" json:"GameType,omitempty"` // 游戏类型
}

func (x *ECMsgRoomCreateReq) Reset() {
	*x = ECMsgRoomCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomCreateReq) ProtoMessage() {}

func (x *ECMsgRoomCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomCreateReq.ProtoReflect.Descriptor instead.
func (*ECMsgRoomCreateReq) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{3}
}

func (x *ECMsgRoomCreateReq) GetGameType() int32 {
	if x != nil {
		return x.GameType
	}
	return 0
}

type ECMsgRoomCreateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomDetail *RoomData `protobuf:"bytes,1,opt,name=RoomDetail,proto3" json:"RoomDetail,omitempty"` // 房间信息
}

func (x *ECMsgRoomCreateRsp) Reset() {
	*x = ECMsgRoomCreateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomCreateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomCreateRsp) ProtoMessage() {}

func (x *ECMsgRoomCreateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomCreateRsp.ProtoReflect.Descriptor instead.
func (*ECMsgRoomCreateRsp) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{4}
}

func (x *ECMsgRoomCreateRsp) GetRoomDetail() *RoomData {
	if x != nil {
		return x.RoomDetail
	}
	return nil
}

// ECMsgRoomQuery  = 2 // 房间查询
type ECMsgRoomQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int64 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *ECMsgRoomQueryReq) Reset() {
	*x = ECMsgRoomQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomQueryReq) ProtoMessage() {}

func (x *ECMsgRoomQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomQueryReq.ProtoReflect.Descriptor instead.
func (*ECMsgRoomQueryReq) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{5}
}

func (x *ECMsgRoomQueryReq) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ECMsgRoomQueryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomInfoList []*RoomSimple `protobuf:"bytes,1,rep,name=RoomInfoList,proto3" json:"RoomInfoList,omitempty"`
}

func (x *ECMsgRoomQueryRsp) Reset() {
	*x = ECMsgRoomQueryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomQueryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomQueryRsp) ProtoMessage() {}

func (x *ECMsgRoomQueryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomQueryRsp.ProtoReflect.Descriptor instead.
func (*ECMsgRoomQueryRsp) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{6}
}

func (x *ECMsgRoomQueryRsp) GetRoomInfoList() []*RoomSimple {
	if x != nil {
		return x.RoomInfoList
	}
	return nil
}

// ECMsgRoomEnter  = 3 // 进入房间
type ECMsgRoomEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int64 `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *ECMsgRoomEnterReq) Reset() {
	*x = ECMsgRoomEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomEnterReq) ProtoMessage() {}

func (x *ECMsgRoomEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomEnterReq.ProtoReflect.Descriptor instead.
func (*ECMsgRoomEnterReq) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{7}
}

func (x *ECMsgRoomEnterReq) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ECMsgRoomEnterRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomDetail *RoomData `protobuf:"bytes,1,opt,name=RoomDetail,proto3" json:"RoomDetail,omitempty"` // 房间信息
}

func (x *ECMsgRoomEnterRsp) Reset() {
	*x = ECMsgRoomEnterRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomEnterRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomEnterRsp) ProtoMessage() {}

func (x *ECMsgRoomEnterRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomEnterRsp.ProtoReflect.Descriptor instead.
func (*ECMsgRoomEnterRsp) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{8}
}

func (x *ECMsgRoomEnterRsp) GetRoomDetail() *RoomData {
	if x != nil {
		return x.RoomDetail
	}
	return nil
}

// ECMsgRoomPushPlayerEnter = 4 // 推送有玩家进入房间
type ECMsgRoomPushPlayerEnterNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID     int64       `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	PlayerInfo *RoomPlayer `protobuf:"bytes,2,opt,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"`
}

func (x *ECMsgRoomPushPlayerEnterNotify) Reset() {
	*x = ECMsgRoomPushPlayerEnterNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomPushPlayerEnterNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomPushPlayerEnterNotify) ProtoMessage() {}

func (x *ECMsgRoomPushPlayerEnterNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomPushPlayerEnterNotify.ProtoReflect.Descriptor instead.
func (*ECMsgRoomPushPlayerEnterNotify) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{9}
}

func (x *ECMsgRoomPushPlayerEnterNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ECMsgRoomPushPlayerEnterNotify) GetPlayerInfo() *RoomPlayer {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// ECMsgRoomLeave           = 5 // 离开房间
type ECMsgRoomLeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgRoomLeaveReq) Reset() {
	*x = ECMsgRoomLeaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomLeaveReq) ProtoMessage() {}

func (x *ECMsgRoomLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomLeaveReq.ProtoReflect.Descriptor instead.
func (*ECMsgRoomLeaveReq) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{10}
}

type ECMsgRoomLeaveRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgRoomLeaveRsp) Reset() {
	*x = ECMsgRoomLeaveRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomLeaveRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomLeaveRsp) ProtoMessage() {}

func (x *ECMsgRoomLeaveRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomLeaveRsp.ProtoReflect.Descriptor instead.
func (*ECMsgRoomLeaveRsp) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{11}
}

// ECMsgRoomPushPlayerLeave   = 6 // 推送有玩家离开房间
type ECMsgRoomPushPlayerLeaveNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *ECMsgRoomPushPlayerLeaveNotify) Reset() {
	*x = ECMsgRoomPushPlayerLeaveNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomPushPlayerLeaveNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomPushPlayerLeaveNotify) ProtoMessage() {}

func (x *ECMsgRoomPushPlayerLeaveNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomPushPlayerLeaveNotify.ProtoReflect.Descriptor instead.
func (*ECMsgRoomPushPlayerLeaveNotify) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{12}
}

func (x *ECMsgRoomPushPlayerLeaveNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

// ECMsgRoomPushPlayerOffline = 7 // 推送有玩家离线
type ECMsgRoomPushPlayerOfflineNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *ECMsgRoomPushPlayerOfflineNotify) Reset() {
	*x = ECMsgRoomPushPlayerOfflineNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomPushPlayerOfflineNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomPushPlayerOfflineNotify) ProtoMessage() {}

func (x *ECMsgRoomPushPlayerOfflineNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomPushPlayerOfflineNotify.ProtoReflect.Descriptor instead.
func (*ECMsgRoomPushPlayerOfflineNotify) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{13}
}

func (x *ECMsgRoomPushPlayerOfflineNotify) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

// ECMsgRoomChat              = 8 // 房间聊天
type ECMsgRoomChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TalkContent string `protobuf:"bytes,1,opt,name=TalkContent,proto3" json:"TalkContent,omitempty"` // 聊天内容
}

func (x *ECMsgRoomChatReq) Reset() {
	*x = ECMsgRoomChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomChatReq) ProtoMessage() {}

func (x *ECMsgRoomChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomChatReq.ProtoReflect.Descriptor instead.
func (*ECMsgRoomChatReq) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{14}
}

func (x *ECMsgRoomChatReq) GetTalkContent() string {
	if x != nil {
		return x.TalkContent
	}
	return ""
}

type ECMsgRoomChatRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ECMsgRoomChatRsp) Reset() {
	*x = ECMsgRoomChatRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomChatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomChatRsp) ProtoMessage() {}

func (x *ECMsgRoomChatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomChatRsp.ProtoReflect.Descriptor instead.
func (*ECMsgRoomChatRsp) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{15}
}

// //ECMsgRoomPushChat          = 9 // 房间聊天-推送
type ECMsgRoomPushChatNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Talker      *RoomTalker `protobuf:"bytes,1,opt,name=Talker,proto3" json:"Talker,omitempty"`           // 说话的人
	TalkContent string      `protobuf:"bytes,2,opt,name=TalkContent,proto3" json:"TalkContent,omitempty"` // 聊天内容
}

func (x *ECMsgRoomPushChatNotify) Reset() {
	*x = ECMsgRoomPushChatNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgRoomPushChatNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgRoomPushChatNotify) ProtoMessage() {}

func (x *ECMsgRoomPushChatNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgRoomPushChatNotify.ProtoReflect.Descriptor instead.
func (*ECMsgRoomPushChatNotify) Descriptor() ([]byte, []int) {
	return file_c_room_proto_rawDescGZIP(), []int{16}
}

func (x *ECMsgRoomPushChatNotify) GetTalker() *RoomTalker {
	if x != nil {
		return x.Talker
	}
	return nil
}

func (x *ECMsgRoomPushChatNotify) GetTalkContent() string {
	if x != nil {
		return x.TalkContent
	}
	return ""
}

var File_c_room_proto protoreflect.FileDescriptor

var file_c_room_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x63, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x67, 0x75, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x17, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6d, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x63, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x5f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5a, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x6a, 0x0a, 0x0a, 0x52,
	0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x63, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0xf3, 0x03, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x44, 0x72, 0x61, 0x77,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x72,
	0x61, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x44, 0x72, 0x61, 0x77, 0x52, 0x6f,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x4e, 0x0a, 0x12, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x6e,
	0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x12,
	0x55, 0x6e, 0x64, 0x65, 0x72, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x4e, 0x0a, 0x12, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x6f, 0x6d, 0x62,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x42, 0x6f, 0x6d, 0x62, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x12,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x6f, 0x6d, 0x62, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x42, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0e, 0x52, 0x65, 0x73, 0x63, 0x75, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x45, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0f, 0x52, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a,
	0x12, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x48, 0x0a, 0x12, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x52,
	0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x2b, 0x0a, 0x11, 0x45, 0x43, 0x4d,
	0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x4d, 0x0a, 0x11, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52,
	0x6f, 0x6f, 0x6d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0c, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f,
	0x6f, 0x6d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x22, 0x47, 0x0a, 0x11, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x6e, 0x0a, 0x1e, 0x45,
	0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x45,
	0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x22, 0x13, 0x0a, 0x11, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x73, 0x70, 0x22, 0x38, 0x0a, 0x1e, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f,
	0x6f, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22,
	0x3a, 0x0a, 0x20, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x73, 0x68,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x34, 0x0a, 0x10, 0x45,
	0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x12, 0x0a, 0x10, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x73, 0x70, 0x22, 0x69, 0x0a, 0x17, 0x45, 0x43, 0x4d, 0x73, 0x67, 0x52, 0x6f,
	0x6f, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x43, 0x68, 0x61, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x2c, 0x0a, 0x06, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x42, 0x1a, 0x5a, 0x18, 0x72, 0x6f, 0x6f, 0x6d, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c_room_proto_rawDescOnce sync.Once
	file_c_room_proto_rawDescData = file_c_room_proto_rawDesc
)

func file_c_room_proto_rawDescGZIP() []byte {
	file_c_room_proto_rawDescOnce.Do(func() {
		file_c_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_room_proto_rawDescData)
	})
	return file_c_room_proto_rawDescData
}

var file_c_room_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_c_room_proto_goTypes = []interface{}{
	(*RoomSimple)(nil),                       // 0: pbclient.RoomSimple
	(*RoomPlayer)(nil),                       // 1: pbclient.RoomPlayer
	(*RoomData)(nil),                         // 2: pbclient.RoomData
	(*ECMsgRoomCreateReq)(nil),               // 3: pbclient.ECMsgRoomCreateReq
	(*ECMsgRoomCreateRsp)(nil),               // 4: pbclient.ECMsgRoomCreateRsp
	(*ECMsgRoomQueryReq)(nil),                // 5: pbclient.ECMsgRoomQueryReq
	(*ECMsgRoomQueryRsp)(nil),                // 6: pbclient.ECMsgRoomQueryRsp
	(*ECMsgRoomEnterReq)(nil),                // 7: pbclient.ECMsgRoomEnterReq
	(*ECMsgRoomEnterRsp)(nil),                // 8: pbclient.ECMsgRoomEnterRsp
	(*ECMsgRoomPushPlayerEnterNotify)(nil),   // 9: pbclient.ECMsgRoomPushPlayerEnterNotify
	(*ECMsgRoomLeaveReq)(nil),                // 10: pbclient.ECMsgRoomLeaveReq
	(*ECMsgRoomLeaveRsp)(nil),                // 11: pbclient.ECMsgRoomLeaveRsp
	(*ECMsgRoomPushPlayerLeaveNotify)(nil),   // 12: pbclient.ECMsgRoomPushPlayerLeaveNotify
	(*ECMsgRoomPushPlayerOfflineNotify)(nil), // 13: pbclient.ECMsgRoomPushPlayerOfflineNotify
	(*ECMsgRoomChatReq)(nil),                 // 14: pbclient.ECMsgRoomChatReq
	(*ECMsgRoomChatRsp)(nil),                 // 15: pbclient.ECMsgRoomChatRsp
	(*ECMsgRoomPushChatNotify)(nil),          // 16: pbclient.ECMsgRoomPushChatNotify
	(*RoomDrawDetail)(nil),                   // 17: pbclient.RoomDrawDetail
	(*RoomUndercoverDetail)(nil),             // 18: pbclient.RoomUndercoverDetail
	(*RoomNumberBombDetail)(nil),             // 19: pbclient.RoomNumberBombDetail
	(*RoomRescueDetail)(nil),                 // 20: pbclient.RoomRescueDetail
	(*RoomRunningDetail)(nil),                // 21: pbclient.RoomRunningDetail
	(*RoomTalker)(nil),                       // 22: pbclient.RoomTalker
}
var file_c_room_proto_depIdxs = []int32{
	1,  // 0: pbclient.RoomData.Players:type_name -> pbclient.RoomPlayer
	17, // 1: pbclient.RoomData.DrawRoomData:type_name -> pbclient.RoomDrawDetail
	18, // 2: pbclient.RoomData.UndercoverRoomData:type_name -> pbclient.RoomUndercoverDetail
	19, // 3: pbclient.RoomData.NumberbombRoomData:type_name -> pbclient.RoomNumberBombDetail
	20, // 4: pbclient.RoomData.RescueRoomData:type_name -> pbclient.RoomRescueDetail
	21, // 5: pbclient.RoomData.RunningRoomData:type_name -> pbclient.RoomRunningDetail
	2,  // 6: pbclient.ECMsgRoomCreateRsp.RoomDetail:type_name -> pbclient.RoomData
	0,  // 7: pbclient.ECMsgRoomQueryRsp.RoomInfoList:type_name -> pbclient.RoomSimple
	2,  // 8: pbclient.ECMsgRoomEnterRsp.RoomDetail:type_name -> pbclient.RoomData
	1,  // 9: pbclient.ECMsgRoomPushPlayerEnterNotify.PlayerInfo:type_name -> pbclient.RoomPlayer
	22, // 10: pbclient.ECMsgRoomPushChatNotify.Talker:type_name -> pbclient.RoomTalker
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_c_room_proto_init() }
func file_c_room_proto_init() {
	if File_c_room_proto != nil {
		return
	}
	file_c_common_proto_init()
	file_c_room_draw_guess_proto_init()
	file_c_room_undercover_proto_init()
	file_c_room_number_bomb_proto_init()
	file_c_room_rescue_proto_init()
	file_c_room_running_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_c_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSimple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomCreateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomQueryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomEnterRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomPushPlayerEnterNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomLeaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomLeaveRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomPushPlayerLeaveNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomPushPlayerOfflineNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomChatRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgRoomPushChatNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_room_proto_goTypes,
		DependencyIndexes: file_c_room_proto_depIdxs,
		MessageInfos:      file_c_room_proto_msgTypes,
	}.Build()
	File_c_room_proto = out.File
	file_c_room_proto_rawDesc = nil
	file_c_room_proto_goTypes = nil
	file_c_room_proto_depIdxs = nil
}
