// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RoleBase struct {
	RoleID     	int64	`gorm:"primary_key"`
	UserID     	int64	`gorm:"user_id"`
	RoleName   	string	`gorm:"role_name"`
	CreateTime 	int64	`gorm:"create_time"`
	Level      	int32	`gorm:"level"`
	LoginTime  	int64	`gorm:"login_time"`
	OfflineTime	int64	`gorm:"offline_time"`
	Money      	int64	`gorm:"money"`
}
func (t *RoleBase) TableName() string {
	return "role_base"
}